--
-- PostgreSQL database dump
--

\restrict Zp7AiKoeyZRUtW1PPIzGF9taOsDJeVF9uB1dYhfSYbP5WFeUDRVpbKOAN13ffe3

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: calificacion_enfermero; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.calificacion_enfermero (
    id_calificacion integer NOT NULL,
    id_enfermero integer NOT NULL,
    puntaje smallint NOT NULL,
    fecha date NOT NULL,
    id_paciente integer,
    comentario text,
    CONSTRAINT chk_califenf_puntaje CHECK (((puntaje >= 1) AND (puntaje <= 5)))
);


--
-- Name: TABLE calificacion_enfermero; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.calificacion_enfermero IS 'Calificacion de calidad registrada para un enfermero';


--
-- Name: calificacion_enfermero_id_calificacion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.calificacion_enfermero ALTER COLUMN id_calificacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calificacion_enfermero_id_calificacion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: calificacion_hospital; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.calificacion_hospital (
    id_calificacion integer NOT NULL,
    id_hospital integer NOT NULL,
    puntaje smallint NOT NULL,
    fecha date NOT NULL,
    id_paciente integer,
    comentario text,
    CONSTRAINT chk_califhosp_puntaje CHECK (((puntaje >= 1) AND (puntaje <= 5)))
);


--
-- Name: TABLE calificacion_hospital; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.calificacion_hospital IS 'Calificacion de calidad registrada para un hospital';


--
-- Name: calificacion_hospital_id_calificacion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.calificacion_hospital ALTER COLUMN id_calificacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calificacion_hospital_id_calificacion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: calificacion_medico; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.calificacion_medico (
    id_calificacion integer NOT NULL,
    id_medico integer NOT NULL,
    puntaje smallint NOT NULL,
    fecha date NOT NULL,
    id_paciente integer,
    comentario text,
    CONSTRAINT chk_califmed_puntaje CHECK (((puntaje >= 1) AND (puntaje <= 5)))
);


--
-- Name: TABLE calificacion_medico; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.calificacion_medico IS 'Calificacion de calidad registrada para un medico';


--
-- Name: calificacion_medico_id_calificacion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.calificacion_medico ALTER COLUMN id_calificacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calificacion_medico_id_calificacion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: calificacion_personal_encargado; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.calificacion_personal_encargado (
    id_calificacion integer NOT NULL,
    id_encargado integer NOT NULL,
    puntaje smallint NOT NULL,
    fecha date NOT NULL,
    id_paciente integer,
    comentario text,
    CONSTRAINT chk_califenc_puntaje CHECK (((puntaje >= 1) AND (puntaje <= 5)))
);


--
-- Name: TABLE calificacion_personal_encargado; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.calificacion_personal_encargado IS 'Calificacion de calidad registrada para el personal administrativo/encargado del hospital';


--
-- Name: calificacion_personal_encargado_id_calificacion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.calificacion_personal_encargado ALTER COLUMN id_calificacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calificacion_personal_encargado_id_calificacion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: camilla; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.camilla (
    id_camilla integer NOT NULL,
    id_unidad_hospital integer NOT NULL,
    numero integer NOT NULL,
    estado character varying(10) DEFAULT 'Libre'::character varying NOT NULL,
    CONSTRAINT chk_camilla_estado CHECK (((estado)::text = ANY ((ARRAY['Libre'::character varying, 'Ocupada'::character varying])::text[])))
);


--
-- Name: TABLE camilla; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.camilla IS 'Camilla habilitada dentro de una unidad de Emergencias u Hospitalizacion';


--
-- Name: camilla_id_camilla_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.camilla ALTER COLUMN id_camilla ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.camilla_id_camilla_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chequeo_preanestesico; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chequeo_preanestesico (
    id_chequeo integer NOT NULL,
    id_solicitud integer NOT NULL,
    clasificacion_asa character varying(3) NOT NULL,
    id_medico_clasifica integer NOT NULL,
    id_anestesista integer NOT NULL,
    plan_anestesia text,
    CONSTRAINT chk_chequeo_asa CHECK (((clasificacion_asa)::text = ANY ((ARRAY['I'::character varying, 'II'::character varying, 'III'::character varying, 'IV'::character varying, 'V'::character varying, 'VI'::character varying])::text[])))
);


--
-- Name: TABLE chequeo_preanestesico; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.chequeo_preanestesico IS 'Chequeo preanestesico previo a la cirugia: clasificacion ASA y plan de anestesia';


--
-- Name: chequeo_preanestesico_id_chequeo_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chequeo_preanestesico ALTER COLUMN id_chequeo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chequeo_preanestesico_id_chequeo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cirugia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cirugia (
    id_cirugia integer NOT NULL,
    id_solicitud integer NOT NULL,
    id_ingreso integer NOT NULL,
    id_quirofano integer NOT NULL,
    id_enfermero_encargado integer NOT NULL,
    fecha_hora_inicio timestamp without time zone NOT NULL,
    fecha_hora_fin timestamp without time zone,
    costo numeric(10,2),
    CONSTRAINT chk_cirugia_costo CHECK (((costo IS NULL) OR (costo >= (0)::numeric))),
    CONSTRAINT chk_cirugia_fin_posterior CHECK (((fecha_hora_fin IS NULL) OR (fecha_hora_fin >= fecha_hora_inicio)))
);


--
-- Name: TABLE cirugia; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.cirugia IS 'Evento intraoperatorio real: ejecucion de una solicitud de cirugia aprobada';


--
-- Name: cirugia_id_cirugia_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cirugia ALTER COLUMN id_cirugia ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cirugia_id_cirugia_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cita_programada; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cita_programada (
    id_cita integer NOT NULL,
    id_paciente integer NOT NULL,
    id_medico integer NOT NULL,
    fecha date NOT NULL,
    hora time without time zone NOT NULL,
    estado character varying(15) DEFAULT 'Programada'::character varying NOT NULL,
    consultorio character varying(20),
    CONSTRAINT chk_cita_estado CHECK (((estado)::text = ANY ((ARRAY['Programada'::character varying, 'Realizada'::character varying, 'Reprogramada'::character varying, 'Cancelada'::character varying])::text[])))
);


--
-- Name: TABLE cita_programada; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.cita_programada IS 'Cita de consulta externa asignada via telefono, correo o recepcion general';


--
-- Name: cita_programada_id_cita_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cita_programada ALTER COLUMN id_cita ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cita_programada_id_cita_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consentimiento_informado; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.consentimiento_informado (
    id_consentimiento integer NOT NULL,
    id_solicitud integer NOT NULL,
    nombre_procedimiento character varying(150) NOT NULL,
    objetivo text NOT NULL,
    id_medico integer NOT NULL,
    firma_paciente character varying(150) NOT NULL,
    fecha date NOT NULL,
    caracteristicas text,
    riesgos text
);


--
-- Name: TABLE consentimiento_informado; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.consentimiento_informado IS 'Consentimiento informado firmado antes de la cirugia (paciente, familiar, tutor o representante)';


--
-- Name: consentimiento_informado_id_consentimiento_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.consentimiento_informado ALTER COLUMN id_consentimiento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consentimiento_informado_id_consentimiento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consulta_paciente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.consulta_paciente (
    id_consulta integer NOT NULL,
    id_paciente integer NOT NULL,
    id_medico integer NOT NULL,
    fecha date NOT NULL,
    tipo_consulta character varying(15) NOT NULL,
    referido_institucion boolean DEFAULT false NOT NULL,
    id_cita integer,
    diagnostico text,
    notas text,
    CONSTRAINT chk_consulta_tipo CHECK (((tipo_consulta)::text = ANY ((ARRAY['Primera'::character varying, 'Reconsulta'::character varying])::text[])))
);


--
-- Name: TABLE consulta_paciente; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.consulta_paciente IS 'Ficha de consulta realizada en Consulta Externa (programada o de paciente referido)';


--
-- Name: consulta_paciente_id_consulta_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.consulta_paciente ALTER COLUMN id_consulta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consulta_paciente_id_consulta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cuota; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cuota (
    id_cuota integer NOT NULL,
    id_factura integer NOT NULL,
    numero_cuota integer NOT NULL,
    monto numeric(10,2) NOT NULL,
    fecha_pago date,
    CONSTRAINT chk_cuota_monto CHECK ((monto > (0)::numeric)),
    CONSTRAINT chk_cuota_numero CHECK (((numero_cuota >= 1) AND (numero_cuota <= 12)))
);


--
-- Name: TABLE cuota; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.cuota IS 'Cuota mensual de pago de una factura (hasta 12 pagos)';


--
-- Name: cuota_id_cuota_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cuota ALTER COLUMN id_cuota ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuota_id_cuota_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departamento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.departamento (
    id_departamento integer NOT NULL,
    nombre character varying(100) NOT NULL
);


--
-- Name: TABLE departamento; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.departamento IS 'Catalogo de departamentos de Guatemala, usado en toda direccion registrada';


--
-- Name: departamento_id_departamento_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.departamento ALTER COLUMN id_departamento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departamento_id_departamento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: diagnostico_secundario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.diagnostico_secundario (
    id_diagnostico_secundario integer NOT NULL,
    id_egreso integer NOT NULL,
    descripcion text NOT NULL
);


--
-- Name: TABLE diagnostico_secundario; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.diagnostico_secundario IS 'Diagnostico secundario adicional registrado en una ficha de egreso (relacion 1:N)';


--
-- Name: diagnostico_secundario_id_diagnostico_secundario_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.diagnostico_secundario ALTER COLUMN id_diagnostico_secundario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.diagnostico_secundario_id_diagnostico_secundario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: egreso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.egreso (
    id_egreso integer NOT NULL,
    id_ingreso integer NOT NULL,
    id_medico integer NOT NULL,
    fecha_hora timestamp without time zone NOT NULL,
    diagnostico_principal text NOT NULL,
    motivo_egreso text NOT NULL,
    codigo_egreso character varying(10) NOT NULL,
    egreso_sin_consentimiento boolean DEFAULT false NOT NULL,
    motivo_sin_consentimiento text,
    id_traslado integer,
    dias_hospitalizado integer,
    referido_otro_hospital character varying(150),
    CONSTRAINT chk_egreso_codigo CHECK (((codigo_egreso)::text = ANY ((ARRAY['Vivo'::character varying, 'Muerto'::character varying, 'Embarazo'::character varying, 'Parto'::character varying])::text[]))),
    CONSTRAINT chk_egreso_dias CHECK (((dias_hospitalizado IS NULL) OR (dias_hospitalizado >= 0))),
    CONSTRAINT chk_egreso_motivo_consentimiento CHECK ((((egreso_sin_consentimiento = false) AND (motivo_sin_consentimiento IS NULL)) OR ((egreso_sin_consentimiento = true) AND (motivo_sin_consentimiento IS NOT NULL))))
);


--
-- Name: TABLE egreso; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.egreso IS 'Ficha de egreso: cierra un ingreso, sea por alta, hospitalizacion, cirugia o defuncion';


--
-- Name: egreso_id_egreso_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.egreso ALTER COLUMN id_egreso ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.egreso_id_egreso_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: enfermero; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.enfermero (
    id_enfermero integer NOT NULL,
    nombre character varying(150) NOT NULL,
    dpi character varying(13) NOT NULL,
    tipo_enfermero character varying(20) NOT NULL,
    id_hospital integer NOT NULL,
    CONSTRAINT chk_enfermero_tipo CHECK (((tipo_enfermero)::text = ANY ((ARRAY['Registrado'::character varying, 'Practicante'::character varying])::text[])))
);


--
-- Name: TABLE enfermero; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.enfermero IS 'Enfermero registrado o practicante asignado a un hospital';


--
-- Name: enfermero_id_enfermero_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.enfermero ALTER COLUMN id_enfermero ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enfermero_id_enfermero_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.equipo (
    id_equipo integer NOT NULL,
    nombre character varying(150) NOT NULL,
    tipo character varying(15) NOT NULL,
    funcion character varying(20) NOT NULL,
    descripcion text,
    CONSTRAINT chk_equipo_funcion CHECK (((funcion)::text = ANY ((ARRAY['Exploracion'::character varying, 'Diagnostico'::character varying, 'Tratamiento'::character varying, 'Rehabilitacion'::character varying, 'Otro'::character varying])::text[]))),
    CONSTRAINT chk_equipo_tipo CHECK (((tipo)::text = ANY ((ARRAY['Medico'::character varying, 'Quirurgico'::character varying, 'Otro'::character varying])::text[])))
);


--
-- Name: TABLE equipo; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.equipo IS 'Catalogo de equipos medicos requeridos en una cirugia';


--
-- Name: equipo_id_equipo_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.equipo ALTER COLUMN id_equipo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipo_id_equipo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: especialidad; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.especialidad (
    id_especialidad integer NOT NULL,
    nombre character varying(100) NOT NULL,
    categoria character varying(25) NOT NULL,
    CONSTRAINT chk_especialidad_categoria CHECK (((categoria)::text = ANY ((ARRAY['Consulta_Emergencia'::character varying, 'Cirugia'::character varying, 'Hospitalizacion'::character varying])::text[])))
);


--
-- Name: TABLE especialidad; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.especialidad IS 'Catalogo unico de especialidades/servicios medicos ofrecidos por unidad';


--
-- Name: especialidad_id_especialidad_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.especialidad ALTER COLUMN id_especialidad ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.especialidad_id_especialidad_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: factura; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.factura (
    id_factura integer NOT NULL,
    id_hospital integer NOT NULL,
    id_paciente integer NOT NULL,
    fecha date NOT NULL,
    descripcion text NOT NULL,
    monto numeric(10,2) NOT NULL,
    id_consulta integer,
    id_ingreso integer,
    CONSTRAINT chk_factura_monto CHECK ((monto > (0)::numeric)),
    CONSTRAINT chk_factura_origen_exclusivo CHECK ((((id_consulta IS NOT NULL) AND (id_ingreso IS NULL)) OR ((id_consulta IS NULL) AND (id_ingreso IS NOT NULL))))
);


--
-- Name: TABLE factura; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.factura IS 'Factura emitida al cancelar el servicio, ya sea de Consulta Externa o de una unidad de internamiento';


--
-- Name: factura_id_factura_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.factura ALTER COLUMN id_factura ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.factura_id_factura_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hospital; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hospital (
    id_hospital integer NOT NULL,
    nombre character varying(150) NOT NULL,
    direccion character varying(200) NOT NULL,
    id_municipio integer NOT NULL,
    telefono character varying(20)
);


--
-- Name: TABLE hospital; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.hospital IS 'Cada uno de los hospitales que conforman la cadena Hospitales de Occidente';


--
-- Name: hospital_id_hospital_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hospital ALTER COLUMN id_hospital ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hospital_id_hospital_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hospitalizacion_detalle; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hospitalizacion_detalle (
    id_hospitalizacion_detalle integer NOT NULL,
    id_ingreso integer NOT NULL,
    id_servicio integer NOT NULL,
    id_camilla integer NOT NULL,
    costo_dia numeric(10,2),
    dias integer,
    CONSTRAINT chk_hospdet_costo_dia CHECK (((costo_dia IS NULL) OR (costo_dia >= (0)::numeric))),
    CONSTRAINT chk_hospdet_dias CHECK (((dias IS NULL) OR (dias >= 0)))
);


--
-- Name: TABLE hospitalizacion_detalle; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.hospitalizacion_detalle IS 'Detalle de la estadia de hospitalizacion asociada a un ingreso (servicio, camilla y costo)';


--
-- Name: hospitalizacion_detalle_id_hospitalizacion_detalle_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hospitalizacion_detalle ALTER COLUMN id_hospitalizacion_detalle ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hospitalizacion_detalle_id_hospitalizacion_detalle_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ingreso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ingreso (
    id_ingreso integer NOT NULL,
    id_paciente integer NOT NULL,
    id_unidad_hospital integer NOT NULL,
    id_medico integer NOT NULL,
    fecha_hora timestamp without time zone NOT NULL,
    motivo_ingreso text NOT NULL,
    id_responsable integer,
    id_camilla integer,
    diagnostico_presuntivo text
);


--
-- Name: TABLE ingreso; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.ingreso IS 'Ficha de ingreso: registra el estado del paciente al ingresar a Emergencias, Cirugia u Hospitalizacion';


--
-- Name: ingreso_id_ingreso_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ingreso ALTER COLUMN id_ingreso ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ingreso_id_ingreso_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: instrumento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.instrumento (
    id_instrumento integer NOT NULL,
    nombre character varying(150) NOT NULL,
    tipo character varying(15) NOT NULL,
    funcion character varying(20) NOT NULL,
    descripcion text,
    CONSTRAINT chk_instrumento_funcion CHECK (((funcion)::text = ANY ((ARRAY['Corte'::character varying, 'Contencion'::character varying, 'Hemostatica'::character varying, 'Retractor'::character varying, 'Accesorio'::character varying, 'Implante'::character varying, 'Otro'::character varying])::text[]))),
    CONSTRAINT chk_instrumento_tipo CHECK (((tipo)::text = ANY ((ARRAY['Medico'::character varying, 'Quirurgico'::character varying, 'Otro'::character varying])::text[])))
);


--
-- Name: TABLE instrumento; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.instrumento IS 'Catalogo de instrumental quirurgico requerido en una cirugia';


--
-- Name: instrumento_id_instrumento_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.instrumento ALTER COLUMN id_instrumento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.instrumento_id_instrumento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: insumo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.insumo (
    id_insumo integer NOT NULL,
    nombre character varying(150) NOT NULL,
    material character varying(100) NOT NULL,
    tipo character varying(15) NOT NULL,
    descripcion text,
    CONSTRAINT chk_insumo_tipo CHECK (((tipo)::text = ANY ((ARRAY['Medico'::character varying, 'Quirurgico'::character varying, 'Otro'::character varying])::text[])))
);


--
-- Name: TABLE insumo; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.insumo IS 'Catalogo de insumos que se pueden requerir y utilizar en una cirugia';


--
-- Name: insumo_id_insumo_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.insumo ALTER COLUMN id_insumo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.insumo_id_insumo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: insumo_utilizado_cirugia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.insumo_utilizado_cirugia (
    id_cirugia integer NOT NULL,
    id_insumo integer NOT NULL,
    cantidad integer NOT NULL,
    CONSTRAINT chk_insumoused_cantidad CHECK ((cantidad > 0))
);


--
-- Name: TABLE insumo_utilizado_cirugia; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.insumo_utilizado_cirugia IS 'Insumos efectivamente utilizados durante una cirugia (base para el calculo del costo)';


--
-- Name: medicamento_recetado; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.medicamento_recetado (
    id_medicamento_recetado integer NOT NULL,
    id_receta integer NOT NULL,
    nombre character varying(150) NOT NULL,
    dosis character varying(100) NOT NULL,
    duracion character varying(100) NOT NULL
);


--
-- Name: TABLE medicamento_recetado; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.medicamento_recetado IS 'Medicamento individual prescrito dentro de una receta medica';


--
-- Name: medicamento_recetado_id_medicamento_recetado_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.medicamento_recetado ALTER COLUMN id_medicamento_recetado ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medicamento_recetado_id_medicamento_recetado_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medico; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.medico (
    id_medico integer NOT NULL,
    nombre character varying(150) NOT NULL,
    dpi character varying(13) NOT NULL,
    id_especialidad integer NOT NULL,
    tipo_medico character varying(20) NOT NULL,
    id_hospital integer NOT NULL,
    telefono character varying(20),
    id_municipio integer,
    area character varying(10),
    CONSTRAINT chk_medico_area CHECK (((area IS NULL) OR ((area)::text = ANY ((ARRAY['Urbana'::character varying, 'Rural'::character varying])::text[])))),
    CONSTRAINT chk_medico_tipo CHECK (((tipo_medico)::text = ANY ((ARRAY['Residente'::character varying, 'Interno'::character varying, 'Externo'::character varying])::text[])))
);


--
-- Name: TABLE medico; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.medico IS 'Medico que atiende en un hospital, en alguna de sus unidades';


--
-- Name: medico_id_medico_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.medico ALTER COLUMN id_medico ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medico_id_medico_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: municipio; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.municipio (
    id_municipio integer NOT NULL,
    id_departamento integer NOT NULL,
    nombre character varying(100) NOT NULL
);


--
-- Name: TABLE municipio; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.municipio IS 'Catalogo de municipios; cada uno pertenece a un unico departamento';


--
-- Name: municipio_id_municipio_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.municipio ALTER COLUMN id_municipio ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.municipio_id_municipio_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: paciente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.paciente (
    id_paciente integer NOT NULL,
    no_expediente character varying(20) NOT NULL,
    nombres character varying(100) NOT NULL,
    apellidos character varying(100) NOT NULL,
    sexo character(1) NOT NULL,
    fecha_nacimiento date NOT NULL,
    id_municipio integer NOT NULL,
    area character varying(10) NOT NULL,
    dpi character varying(13),
    telefono character varying(20),
    no_seguro_social character varying(20),
    CONSTRAINT chk_paciente_area CHECK (((area)::text = ANY ((ARRAY['Urbana'::character varying, 'Rural'::character varying])::text[]))),
    CONSTRAINT chk_paciente_fecha_nacimiento CHECK ((fecha_nacimiento <= CURRENT_DATE)),
    CONSTRAINT chk_paciente_sexo CHECK ((sexo = ANY (ARRAY['M'::bpchar, 'F'::bpchar])))
);


--
-- Name: TABLE paciente; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.paciente IS 'Paciente atendido en cualquier unidad de cualquier hospital de la cadena';


--
-- Name: paciente_id_paciente_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.paciente ALTER COLUMN id_paciente ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paciente_id_paciente_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personal_encargado; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personal_encargado (
    id_encargado integer NOT NULL,
    nombre character varying(150) NOT NULL,
    dpi character varying(13) NOT NULL,
    puesto character varying(100) NOT NULL,
    id_hospital integer NOT NULL,
    telefono character varying(20)
);


--
-- Name: TABLE personal_encargado; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.personal_encargado IS 'Personal administrativo/encargado de un hospital, sujeto de calificacion de calidad (distinto del responsable del paciente)';


--
-- Name: personal_encargado_id_encargado_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personal_encargado ALTER COLUMN id_encargado ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personal_encargado_id_encargado_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quirofano; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quirofano (
    id_quirofano integer NOT NULL,
    id_hospital integer NOT NULL,
    numero integer NOT NULL,
    estado character varying(10) DEFAULT 'Libre'::character varying NOT NULL,
    CONSTRAINT chk_quirofano_estado CHECK (((estado)::text = ANY ((ARRAY['Libre'::character varying, 'Ocupado'::character varying])::text[])))
);


--
-- Name: TABLE quirofano; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.quirofano IS 'Quirofano habilitado de un hospital (cada hospital cuenta con varios)';


--
-- Name: quirofano_id_quirofano_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quirofano ALTER COLUMN id_quirofano ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quirofano_id_quirofano_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: receta_medica; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.receta_medica (
    id_receta integer NOT NULL,
    id_consulta integer NOT NULL,
    fecha date NOT NULL,
    id_hospital integer NOT NULL,
    proxima_cita date,
    numero_clinica character varying(20)
);


--
-- Name: TABLE receta_medica; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.receta_medica IS 'Receta medica emitida al finalizar una consulta de Consulta Externa';


--
-- Name: receta_medica_id_receta_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.receta_medica ALTER COLUMN id_receta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.receta_medica_id_receta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registro_procedimiento_cirugia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registro_procedimiento_cirugia (
    id_registro integer NOT NULL,
    id_cirugia integer NOT NULL,
    etapa character varying(15) NOT NULL,
    procedimiento character varying(150) NOT NULL,
    resultado character varying(25) NOT NULL,
    hora_registro timestamp without time zone NOT NULL,
    id_enfermero integer NOT NULL,
    descripcion text,
    CONSTRAINT chk_registro_etapa CHECK (((etapa)::text = ANY ((ARRAY['Preoperatorio'::character varying, 'Intraoperatorio'::character varying, 'Postoperatorio'::character varying])::text[]))),
    CONSTRAINT chk_registro_resultado CHECK (((resultado)::text = ANY ((ARRAY['Aceptable'::character varying, 'Medianamente aceptable'::character varying, 'No aceptable'::character varying, 'Exito'::character varying, 'Falla'::character varying])::text[])))
);


--
-- Name: TABLE registro_procedimiento_cirugia; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.registro_procedimiento_cirugia IS 'Registro normalizado de todos los checklists de la cirugia (preoperatorio, chequeo en quirofano, pausa quirurgica, cuidados intraoperatorios, salida, recuperacion, traslado seguro)';


--
-- Name: registro_procedimiento_cirugia_id_registro_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.registro_procedimiento_cirugia ALTER COLUMN id_registro ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registro_procedimiento_cirugia_id_registro_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: requerimiento_equipo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.requerimiento_equipo (
    id_solicitud integer NOT NULL,
    id_equipo integer NOT NULL,
    cantidad integer NOT NULL,
    CONSTRAINT chk_reqequipo_cantidad CHECK ((cantidad > 0))
);


--
-- Name: TABLE requerimiento_equipo; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.requerimiento_equipo IS 'Resuelve la relacion N:M entre solicitud_cirugia y equipo (llave primaria compuesta)';


--
-- Name: requerimiento_instrumento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.requerimiento_instrumento (
    id_solicitud integer NOT NULL,
    id_instrumento integer NOT NULL,
    cantidad integer NOT NULL,
    CONSTRAINT chk_reqinstr_cantidad CHECK ((cantidad > 0))
);


--
-- Name: TABLE requerimiento_instrumento; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.requerimiento_instrumento IS 'Resuelve la relacion N:M entre solicitud_cirugia e instrumento (llave primaria compuesta)';


--
-- Name: requerimiento_insumo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.requerimiento_insumo (
    id_solicitud integer NOT NULL,
    id_insumo integer NOT NULL,
    cantidad integer NOT NULL,
    CONSTRAINT chk_reqinsumo_cantidad CHECK ((cantidad > 0))
);


--
-- Name: TABLE requerimiento_insumo; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.requerimiento_insumo IS 'Resuelve la relacion N:M entre solicitud_cirugia e insumo (llave primaria compuesta)';


--
-- Name: responsable_paciente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.responsable_paciente (
    id_responsable integer NOT NULL,
    id_paciente integer NOT NULL,
    nombre character varying(150) NOT NULL,
    parentesco character varying(50) NOT NULL,
    dpi character varying(13),
    telefono character varying(20),
    id_municipio integer,
    area character varying(10),
    CONSTRAINT chk_responsable_area CHECK (((area IS NULL) OR ((area)::text = ANY ((ARRAY['Urbana'::character varying, 'Rural'::character varying])::text[]))))
);


--
-- Name: TABLE responsable_paciente; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.responsable_paciente IS 'Familiar o responsable del paciente registrado en la ficha de ingreso (no es personal del hospital)';


--
-- Name: responsable_paciente_id_responsable_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.responsable_paciente ALTER COLUMN id_responsable ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.responsable_paciente_id_responsable_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: servicio_hospitalizacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.servicio_hospitalizacion (
    id_servicio integer NOT NULL,
    nombre character varying(100) NOT NULL
);


--
-- Name: TABLE servicio_hospitalizacion; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.servicio_hospitalizacion IS 'Catalogo de servicios de Hospitalizacion (Hematologia, Medicina interna, Neumologia, Oncologia, Ortopedia, Pediatria, cuidados intermedios, cuidado critico)';


--
-- Name: servicio_hospitalizacion_id_servicio_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.servicio_hospitalizacion ALTER COLUMN id_servicio ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.servicio_hospitalizacion_id_servicio_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solicitud_cirugia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solicitud_cirugia (
    id_solicitud integer NOT NULL,
    id_paciente integer NOT NULL,
    id_cirujano integer NOT NULL,
    caracter character varying(15) NOT NULL,
    tipo_procedimiento character varying(150) NOT NULL,
    fecha_hora_solicitud timestamp without time zone NOT NULL,
    estado character varying(15) DEFAULT 'Pendiente'::character varying NOT NULL,
    id_hospital integer NOT NULL,
    historia_clinica text,
    tiempo_estimado interval,
    tipo_anestesia character varying(100),
    motivo_rechazo text,
    id_quirofano integer,
    fecha_hora_agendada timestamp without time zone,
    CONSTRAINT chk_solicitud_caracter CHECK (((caracter)::text = ANY ((ARRAY['Urgente'::character varying, 'Programado'::character varying])::text[]))),
    CONSTRAINT chk_solicitud_estado CHECK (((estado)::text = ANY ((ARRAY['Pendiente'::character varying, 'Aprobada'::character varying, 'Rechazada'::character varying])::text[]))),
    CONSTRAINT chk_solicitud_motivo_rechazo CHECK (((((estado)::text = 'Rechazada'::text) AND (motivo_rechazo IS NOT NULL)) OR (((estado)::text <> 'Rechazada'::text) AND (motivo_rechazo IS NULL))))
);


--
-- Name: TABLE solicitud_cirugia; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.solicitud_cirugia IS 'Agendamiento quirurgico solicitado por el cirujano, revisado por el comite medico';


--
-- Name: solicitud_cirugia_id_solicitud_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solicitud_cirugia ALTER COLUMN id_solicitud ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solicitud_cirugia_id_solicitud_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: traslado; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.traslado (
    id_traslado integer NOT NULL,
    id_paciente integer NOT NULL,
    id_medico_indica integer NOT NULL,
    fecha_hora timestamp without time zone NOT NULL,
    id_unidad_destino integer NOT NULL,
    interno_destino boolean NOT NULL,
    id_unidad_origen integer,
    interno_origen boolean
);


--
-- Name: TABLE traslado; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.traslado IS 'Ficha de traslado de un paciente entre unidades (o desde/hacia otra institucion)';


--
-- Name: traslado_id_traslado_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.traslado ALTER COLUMN id_traslado ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.traslado_id_traslado_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: unidad_hospital; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unidad_hospital (
    id_unidad_hospital integer NOT NULL,
    id_hospital integer NOT NULL,
    tipo_unidad character varying(20) NOT NULL,
    CONSTRAINT chk_unidadhosp_tipo CHECK (((tipo_unidad)::text = ANY ((ARRAY['Emergencias'::character varying, 'Cirugia'::character varying, 'Hospitalizacion'::character varying])::text[])))
);


--
-- Name: TABLE unidad_hospital; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.unidad_hospital IS 'Unidad medica (Emergencias/Cirugia/Hospitalizacion) concreta de un hospital especifico';


--
-- Name: unidad_hospital_id_unidad_hospital_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.unidad_hospital ALTER COLUMN id_unidad_hospital ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unidad_hospital_id_unidad_hospital_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: calificacion_enfermero; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.calificacion_enfermero (id_calificacion, id_enfermero, puntaje, fecha, id_paciente, comentario) FROM stdin;
1	1	4	2026-09-23	2	Muy atenta durante la recuperacion postoperatoria
\.


--
-- Data for Name: calificacion_hospital; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.calificacion_hospital (id_calificacion, id_hospital, puntaje, fecha, id_paciente, comentario) FROM stdin;
1	1	5	2026-09-23	2	Excelente atencion durante la cirugia de emergencia
\.


--
-- Data for Name: calificacion_medico; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.calificacion_medico (id_calificacion, id_medico, puntaje, fecha, id_paciente, comentario) FROM stdin;
1	6	5	2026-09-23	2	El cirujano explico todo el procedimiento con claridad
\.


--
-- Data for Name: calificacion_personal_encargado; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.calificacion_personal_encargado (id_calificacion, id_encargado, puntaje, fecha, id_paciente, comentario) FROM stdin;
1	1	4	2026-09-10	1	Buena atencion en la recepcion del hospital
\.


--
-- Data for Name: camilla; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.camilla (id_camilla, id_unidad_hospital, numero, estado) FROM stdin;
1	1	1	Ocupada
2	1	2	Libre
3	3	1	Ocupada
4	3	2	Ocupada
5	6	1	Libre
6	4	1	Ocupada
\.


--
-- Data for Name: chequeo_preanestesico; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.chequeo_preanestesico (id_chequeo, id_solicitud, clasificacion_asa, id_medico_clasifica, id_anestesista, plan_anestesia) FROM stdin;
1	1	II	6	8	Anestesia general balanceada
\.


--
-- Data for Name: cirugia; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.cirugia (id_cirugia, id_solicitud, id_ingreso, id_quirofano, id_enfermero_encargado, fecha_hora_inicio, fecha_hora_fin, costo) FROM stdin;
1	1	2	1	1	2026-09-20 16:15:00	2026-09-20 17:45:00	3500.00
\.


--
-- Data for Name: cita_programada; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.cita_programada (id_cita, id_paciente, id_medico, fecha, hora, estado, consultorio) FROM stdin;
1	1	1	2026-09-10	08:00:00	Realizada	Clinica 3
2	4	3	2026-09-15	09:30:00	Realizada	Clinica 5
3	8	2	2026-09-30	10:00:00	Programada	Clinica 2
4	5	1	2026-09-12	11:00:00	Cancelada	Clinica 3
\.


--
-- Data for Name: consentimiento_informado; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.consentimiento_informado (id_consentimiento, id_solicitud, nombre_procedimiento, objetivo, id_medico, firma_paciente, fecha, caracteristicas, riesgos) FROM stdin;
1	1	Apendicectomia convencional	Extirpar el apendice inflamado para evitar complicaciones	6	Jose Manuel Garcia Lopez	2026-09-20	Cirugia abierta bajo anestesia general	Sangrado, infeccion, reaccion anestesica
\.


--
-- Data for Name: consulta_paciente; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.consulta_paciente (id_consulta, id_paciente, id_medico, fecha, tipo_consulta, referido_institucion, id_cita, diagnostico, notas) FROM stdin;
1	1	1	2026-09-10	Primera	f	1	Rinofaringitis aguda	Se indica reposo e hidratacion abundante
2	4	3	2026-09-15	Reconsulta	f	2	Hipertension arterial controlada	Continuar tratamiento, proxima cita en un mes
3	7	4	2026-09-18	Primera	t	\N	Control ginecologico de rutina	Paciente referida del Centro de Salud de Retalhuleu
\.


--
-- Data for Name: cuota; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.cuota (id_cuota, id_factura, numero_cuota, monto, fecha_pago) FROM stdin;
1	1	1	150.00	2026-09-10
2	2	1	4166.67	2026-09-22
3	2	2	4166.67	2026-10-22
4	2	3	4166.66	\N
5	3	1	800.00	2026-09-25
\.


--
-- Data for Name: departamento; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.departamento (id_departamento, nombre) FROM stdin;
1	Quetzaltenango
2	San Marcos
3	Huehuetenango
4	Retalhuleu
5	Totonicapan
\.


--
-- Data for Name: diagnostico_secundario; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.diagnostico_secundario (id_diagnostico_secundario, id_egreso, descripcion) FROM stdin;
1	3	Deshidratacion leve resuelta con hidratacion intravenosa
\.


--
-- Data for Name: egreso; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.egreso (id_egreso, id_ingreso, id_medico, fecha_hora, diagnostico_principal, motivo_egreso, codigo_egreso, egreso_sin_consentimiento, motivo_sin_consentimiento, id_traslado, dias_hospitalizado, referido_otro_hospital) FROM stdin;
1	1	1	2026-09-20 15:00:00	Apendicitis aguda, requiere manejo quirurgico	Traslado a Cirugia	Vivo	f	\N	1	0	\N
2	2	6	2026-09-20 19:00:00	Apendicitis aguda resuelta quirurgicamente	Traslado a Hospitalizacion para recuperacion postoperatoria	Vivo	f	\N	2	\N	\N
3	3	1	2026-09-22 10:00:00	Postoperatorio de apendicectomia sin complicaciones	Alta medica por mejoria	Vivo	f	\N	\N	2	\N
4	4	5	2026-09-25 01:30:00	Crisis asmatica resuelta	Alta por mejoria tras nebulizacion	Vivo	f	\N	\N	0	\N
\.


--
-- Data for Name: enfermero; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.enfermero (id_enfermero, nombre, dpi, tipo_enfermero, id_hospital) FROM stdin;
1	Marta Lidia Ixcoy Us	1212121212121	Registrado	1
2	Jose Domingo Chocoj Tzul	1313131313131	Practicante	1
3	Blanca Estela Vail Marroquin	1414141414141	Registrado	1
4	Wilson Aroldo Giron Argueta	1515151515151	Registrado	2
5	Petrona Us Cotzojay	1616161616161	Practicante	2
6	Hugo Leonel Batz Sican	1717171717171	Registrado	3
\.


--
-- Data for Name: equipo; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.equipo (id_equipo, nombre, tipo, funcion, descripcion) FROM stdin;
1	Maquina de anestesia	Medico	Tratamiento	Equipo para administracion de anestesia general
2	Monitor de signos vitales	Medico	Diagnostico	Monitoreo continuo de signos vitales
3	Electrobisturi	Quirurgico	Tratamiento	Corte y coagulacion por electrocirugia
4	Lampara quirurgica	Quirurgico	Exploracion	Iluminacion del campo quirurgico
\.


--
-- Data for Name: especialidad; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.especialidad (id_especialidad, nombre, categoria) FROM stdin;
1	Cardiologia	Consulta_Emergencia
2	Dermatologia	Consulta_Emergencia
3	Fisioterapia	Consulta_Emergencia
4	Ginecologia Oncologica	Consulta_Emergencia
5	Hematologia	Consulta_Emergencia
6	Medicina Fisica y Rehabilitacion	Consulta_Emergencia
7	Medicina General	Consulta_Emergencia
8	Nutricion y Dietetica	Consulta_Emergencia
9	Odontologia General	Consulta_Emergencia
10	Oftalmologia	Consulta_Emergencia
11	Psicologia	Consulta_Emergencia
12	Pediatria	Consulta_Emergencia
13	Urologia	Consulta_Emergencia
14	Terapia del Lenguaje	Consulta_Emergencia
15	Cirugia Cardiovascular Adulto y Pediatrica	Cirugia
16	Cirugia de la Mano	Cirugia
17	Cirugia General	Cirugia
18	Videolaparoscopia Quirurgica	Cirugia
19	Cirugia Ginecologica	Cirugia
20	Cirugia Neurologica	Cirugia
21	Cirugia Oftalmologica	Cirugia
22	Cirugia Oncologica	Cirugia
23	Cirugia Ortopedica	Cirugia
24	Cirugia Otorrinolaringologica	Cirugia
25	Cirugia Pediatrica	Cirugia
26	Cirugia Plastica	Cirugia
27	Cirugia de Torax	Cirugia
28	Cirugia Urologica	Cirugia
\.


--
-- Data for Name: factura; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.factura (id_factura, id_hospital, id_paciente, fecha, descripcion, monto, id_consulta, id_ingreso) FROM stdin;
1	1	1	2026-09-10	Consulta externa de Medicina General - primera consulta	150.00	1	\N
2	1	2	2026-09-22	Atencion de emergencia, cirugia de apendicectomia y hospitalizacion asociada	12500.00	\N	1
3	2	3	2026-09-25	Atencion de emergencia por crisis asmatica	800.00	\N	4
\.


--
-- Data for Name: hospital; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.hospital (id_hospital, nombre, direccion, id_municipio, telefono) FROM stdin;
1	Hospital Regional de Occidente	0 avenida 5-45, zona 1	1	77612345
2	Hospital Nacional de San Marcos	4a calle 8-20, zona 3	3	77762210
3	Hospital Nacional de Huehuetenango	2a avenida 3-15, zona 2	5	77641180
\.


--
-- Data for Name: hospitalizacion_detalle; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.hospitalizacion_detalle (id_hospitalizacion_detalle, id_ingreso, id_servicio, id_camilla, costo_dia, dias) FROM stdin;
1	3	7	3	350.00	2
2	5	3	4	300.00	\N
\.


--
-- Data for Name: ingreso; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.ingreso (id_ingreso, id_paciente, id_unidad_hospital, id_medico, fecha_hora, motivo_ingreso, id_responsable, id_camilla, diagnostico_presuntivo) FROM stdin;
1	2	1	1	2026-09-20 14:30:00	Dolor abdominal agudo de 12 horas de evolucion	\N	1	Apendicitis aguda probable
2	2	2	6	2026-09-20 16:00:00	Intervencion quirurgica: apendicectomia	\N	\N	Apendicitis aguda
3	2	3	1	2026-09-20 19:15:00	Recuperacion postoperatoria de apendicectomia	\N	3	Postoperatorio de apendicectomia
4	3	4	5	2026-09-24 22:00:00	Crisis asmatica	2	6	Crisis asmatica moderada
5	5	3	1	2026-09-23 09:00:00	Neumonia adquirida en la comunidad	\N	4	Neumonia bacteriana
\.


--
-- Data for Name: instrumento; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.instrumento (id_instrumento, nombre, tipo, funcion, descripcion) FROM stdin;
1	Bisturi No. 4	Quirurgico	Corte	Mango de bisturi con hoja no. 4
2	Pinza Kelly	Quirurgico	Hemostatica	Pinza hemostatica curva
3	Separador de Farabeuf	Quirurgico	Retractor	Separador manual de tejidos
4	Porta-agujas Mayo-Hegar	Quirurgico	Accesorio	Para sutura manual
5	Tijera Metzenbaum	Quirurgico	Corte	Tijera de diseccion de tejido fino
\.


--
-- Data for Name: insumo; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.insumo (id_insumo, nombre, material, tipo, descripcion) FROM stdin;
1	Gasas esteriles	Textil	Quirurgico	Paquete de gasas esteriles para cirugia
2	Suero fisiologico 0.9%	Liquido	Medico	Solucion salina para hidratacion e irrigacion
3	Sutura Vicryl 2-0	Sintetico	Quirurgico	Sutura absorbible
4	Guantes esteriles	Latex	Medico	Guantes quirurgicos esteriles
5	Anestesico local Lidocaina 2%	Liquido	Medico	Anestesico de uso local
\.


--
-- Data for Name: insumo_utilizado_cirugia; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.insumo_utilizado_cirugia (id_cirugia, id_insumo, cantidad) FROM stdin;
1	1	8
1	2	2
1	3	1
\.


--
-- Data for Name: medicamento_recetado; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.medicamento_recetado (id_medicamento_recetado, id_receta, nombre, dosis, duracion) FROM stdin;
1	1	Paracetamol	500 mg cada 6 horas	5 dias
2	1	Loratadina	10 mg cada dia	5 dias
3	2	Losartan	50 mg cada dia	30 dias
\.


--
-- Data for Name: medico; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.medico (id_medico, nombre, dpi, id_especialidad, tipo_medico, id_hospital, telefono, id_municipio, area) FROM stdin;
1	Dr. Luis Fernando Sican Toc	1111222233341	7	Residente	1	77611001	1	Urbana
2	Dra. Gabriela Marisol Cabrera Us	2222333344452	12	Residente	1	77611002	1	Urbana
3	Dr. Edgar Rolando Velasquez Marroquin	3333444455563	1	Interno	1	77611003	\N	\N
4	Dra. Silvia Patricia Xitumul Us	4444555566674	4	Residente	2	77762211	3	Urbana
5	Dr. Mario Estuardo Chocoj Vail	5555666677785	7	Residente	2	77762212	3	Urbana
6	Dr. Julio Cesar Argueta Giron	6666777788896	17	Residente	1	77611006	1	Urbana
7	Dr. Byron Estuardo Giron Cotzojay	7777888899907	23	Externo	1	48870077	\N	\N
8	Dr. Rigoberto Tepaz Chocoj	8888999900018	17	Interno	1	77611008	1	Urbana
9	Dra. Claudia Beatriz Us Batz	9999000011129	7	Residente	3	77641181	5	Urbana
10	Dra. Karla Beatriz Tzul Ixcoy	0000111122230	6	Residente	1	77611010	1	Urbana
\.


--
-- Data for Name: municipio; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.municipio (id_municipio, id_departamento, nombre) FROM stdin;
1	1	Quetzaltenango
2	1	Coatepeque
3	2	San Marcos
4	2	Malacatan
5	3	Huehuetenango
6	3	Jacaltenango
7	4	Retalhuleu
8	4	Champerico
9	5	Totonicapan
10	5	Momostenango
\.


--
-- Data for Name: paciente; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.paciente (id_paciente, no_expediente, nombres, apellidos, sexo, fecha_nacimiento, id_municipio, area, dpi, telefono, no_seguro_social) FROM stdin;
1	EXP-2026-0001	Maria	Xitumul Tzul	F	1990-03-14	1	Urbana	1234567890101	55123456	IGSS-880011
2	EXP-2026-0002	Jose Manuel	Garcia Lopez	M	1975-11-02	2	Rural	2345678901202	42198765	\N
3	EXP-2026-0003	Juana	Us Chocoj	F	2003-07-22	3	Rural	3456789012303	30456789	\N
4	EXP-2026-0004	Carlos Alberto	Morales Ramirez	M	1988-05-30	4	Urbana	4567890123404	51122334	IGSS-770234
5	EXP-2026-0005	Rosa Elvira	Tepaz Batz	F	1965-01-09	5	Urbana	5678901234505	77650099	IGSS-650098
6	EXP-2026-0006	Miguel Angel	De Leon Argueta	M	1999-09-19	6	Rural	6789012345606	48871122	\N
7	EXP-2026-0007	Ana Lucia	Marroquin Giron	F	1980-12-25	7	Urbana	7890123456707	33445566	IGSS-800456
8	EXP-2026-0008	Pedro	Cotzojay Ixcoy	M	2010-02-14	10	Rural	8901234567808	30112233	\N
\.


--
-- Data for Name: personal_encargado; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personal_encargado (id_encargado, nombre, dpi, puesto, id_hospital, telefono) FROM stdin;
1	Sofia Elizabeth Marroquin Toc	2121212121212	Jefa de Recepcion	1	77611020
2	Ruben Alexander Us Giron	2222222222223	Encargado de Admisiones	1	77611021
3	Deysi Marisol Chocoj Argueta	2323232323232	Encargada de Facturacion	2	77762220
4	Anselmo Tzul Vail	2424242424242	Coordinador de Turno	3	77641190
\.


--
-- Data for Name: quirofano; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.quirofano (id_quirofano, id_hospital, numero, estado) FROM stdin;
1	1	1	Ocupado
2	1	2	Libre
3	2	1	Libre
\.


--
-- Data for Name: receta_medica; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.receta_medica (id_receta, id_consulta, fecha, id_hospital, proxima_cita, numero_clinica) FROM stdin;
1	1	2026-09-10	1	2026-10-10	3
2	2	2026-09-15	1	2026-11-15	5
\.


--
-- Data for Name: registro_procedimiento_cirugia; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.registro_procedimiento_cirugia (id_registro, id_cirugia, etapa, procedimiento, resultado, hora_registro, id_enfermero, descripcion) FROM stdin;
1	1	Preoperatorio	Entrada: brazalete de identificacion y ficha clinica	Aceptable	2026-09-20 16:00:00	1	Paciente confirma nombre y procedimiento a realizar
2	1	Intraoperatorio	Chequeo en quirofano	Aceptable	2026-09-20 16:15:00	1	Equipo completo y camilla trasladada correctamente
3	1	Intraoperatorio	Procedimientos de pausa quirurgica	Aceptable	2026-09-20 16:20:00	1	Confirmacion de paciente, equipo y esterilidad
4	1	Intraoperatorio	Gestion de cuidados intraoperatoria: balance hidrico	Exito	2026-09-20 17:00:00	1	Balance hidrico dentro de parametros normales
5	1	Intraoperatorio	Salida quirurgica: conteo de instrumental	Aceptable	2026-09-20 17:40:00	1	Conteo de instrumental satisfactorio, cierre de incision
6	1	Postoperatorio	Ingreso a sala de recuperacion	Exito	2026-09-20 17:50:00	3	Sin complicaciones durante la cirugia
7	1	Postoperatorio	Traslado seguro a Hospitalizacion	Exito	2026-09-20 19:00:00	3	Signos vitales normales, zona operatoria limpia
\.


--
-- Data for Name: requerimiento_equipo; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.requerimiento_equipo (id_solicitud, id_equipo, cantidad) FROM stdin;
1	1	1
1	3	1
\.


--
-- Data for Name: requerimiento_instrumento; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.requerimiento_instrumento (id_solicitud, id_instrumento, cantidad) FROM stdin;
1	1	1
1	2	2
1	5	1
\.


--
-- Data for Name: requerimiento_insumo; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.requerimiento_insumo (id_solicitud, id_insumo, cantidad) FROM stdin;
1	1	10
1	2	2
1	3	1
\.


--
-- Data for Name: responsable_paciente; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.responsable_paciente (id_responsable, id_paciente, nombre, parentesco, dpi, telefono, id_municipio, area) FROM stdin;
1	8	Juana Ixcoy Batz	Madre	9012345678909	30112200	10	Rural
2	3	Domingo Us Sican	Padre	0123456789010	30456700	3	Rural
3	6	Elena Argueta Toc	Hermana	1122334455667	48870000	6	Rural
4	1	Fernando Xitumul Vail	Esposo	2233445566778	55123400	1	Urbana
\.


--
-- Data for Name: servicio_hospitalizacion; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.servicio_hospitalizacion (id_servicio, nombre) FROM stdin;
1	Hematologia
2	Medicina interna
3	Neumologia
4	Oncologia
5	Ortopedia
6	Pediatria
7	Unidad de cuidados intermedios
8	Unidad de cuidado critico de adultos
\.


--
-- Data for Name: solicitud_cirugia; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.solicitud_cirugia (id_solicitud, id_paciente, id_cirujano, caracter, tipo_procedimiento, fecha_hora_solicitud, estado, id_hospital, historia_clinica, tiempo_estimado, tipo_anestesia, motivo_rechazo, id_quirofano, fecha_hora_agendada) FROM stdin;
1	2	6	Urgente	Apendicectomia convencional	2026-09-20 15:10:00	Aprobada	1	Paciente masculino, 51 anios, dolor en fosa iliaca derecha de 12 horas de evolucion	01:30:00	General	\N	1	2026-09-20 16:00:00
2	7	7	Programado	Artroscopia de rodilla	2026-09-18 09:00:00	Rechazada	1	Paciente femenina, 46 anios, gonalgia cronica	02:00:00	Regional	Estudios preoperatorios incompletos: falta evaluacion cardiologica	\N	\N
\.


--
-- Data for Name: traslado; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.traslado (id_traslado, id_paciente, id_medico_indica, fecha_hora, id_unidad_destino, interno_destino, id_unidad_origen, interno_origen) FROM stdin;
1	2	1	2026-09-20 15:00:00	2	t	1	t
2	2	6	2026-09-20 19:00:00	3	t	2	t
\.


--
-- Data for Name: unidad_hospital; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.unidad_hospital (id_unidad_hospital, id_hospital, tipo_unidad) FROM stdin;
1	1	Emergencias
2	1	Cirugia
3	1	Hospitalizacion
4	2	Emergencias
5	2	Cirugia
6	2	Hospitalizacion
7	3	Emergencias
8	3	Cirugia
9	3	Hospitalizacion
\.


--
-- Name: calificacion_enfermero_id_calificacion_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.calificacion_enfermero_id_calificacion_seq', 1, true);


--
-- Name: calificacion_hospital_id_calificacion_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.calificacion_hospital_id_calificacion_seq', 1, true);


--
-- Name: calificacion_medico_id_calificacion_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.calificacion_medico_id_calificacion_seq', 1, true);


--
-- Name: calificacion_personal_encargado_id_calificacion_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.calificacion_personal_encargado_id_calificacion_seq', 1, true);


--
-- Name: camilla_id_camilla_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.camilla_id_camilla_seq', 6, true);


--
-- Name: chequeo_preanestesico_id_chequeo_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.chequeo_preanestesico_id_chequeo_seq', 1, true);


--
-- Name: cirugia_id_cirugia_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.cirugia_id_cirugia_seq', 1, true);


--
-- Name: cita_programada_id_cita_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.cita_programada_id_cita_seq', 4, true);


--
-- Name: consentimiento_informado_id_consentimiento_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.consentimiento_informado_id_consentimiento_seq', 1, true);


--
-- Name: consulta_paciente_id_consulta_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.consulta_paciente_id_consulta_seq', 3, true);


--
-- Name: cuota_id_cuota_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.cuota_id_cuota_seq', 5, true);


--
-- Name: departamento_id_departamento_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.departamento_id_departamento_seq', 6, true);


--
-- Name: diagnostico_secundario_id_diagnostico_secundario_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.diagnostico_secundario_id_diagnostico_secundario_seq', 1, true);


--
-- Name: egreso_id_egreso_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.egreso_id_egreso_seq', 4, true);


--
-- Name: enfermero_id_enfermero_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.enfermero_id_enfermero_seq', 6, true);


--
-- Name: equipo_id_equipo_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.equipo_id_equipo_seq', 4, true);


--
-- Name: especialidad_id_especialidad_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.especialidad_id_especialidad_seq', 28, true);


--
-- Name: factura_id_factura_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.factura_id_factura_seq', 3, true);


--
-- Name: hospital_id_hospital_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.hospital_id_hospital_seq', 3, true);


--
-- Name: hospitalizacion_detalle_id_hospitalizacion_detalle_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.hospitalizacion_detalle_id_hospitalizacion_detalle_seq', 2, true);


--
-- Name: ingreso_id_ingreso_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.ingreso_id_ingreso_seq', 5, true);


--
-- Name: instrumento_id_instrumento_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.instrumento_id_instrumento_seq', 5, true);


--
-- Name: insumo_id_insumo_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.insumo_id_insumo_seq', 5, true);


--
-- Name: medicamento_recetado_id_medicamento_recetado_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.medicamento_recetado_id_medicamento_recetado_seq', 3, true);


--
-- Name: medico_id_medico_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.medico_id_medico_seq', 10, true);


--
-- Name: municipio_id_municipio_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.municipio_id_municipio_seq', 10, true);


--
-- Name: paciente_id_paciente_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.paciente_id_paciente_seq', 8, true);


--
-- Name: personal_encargado_id_encargado_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personal_encargado_id_encargado_seq', 4, true);


--
-- Name: quirofano_id_quirofano_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.quirofano_id_quirofano_seq', 3, true);


--
-- Name: receta_medica_id_receta_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.receta_medica_id_receta_seq', 2, true);


--
-- Name: registro_procedimiento_cirugia_id_registro_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.registro_procedimiento_cirugia_id_registro_seq', 7, true);


--
-- Name: responsable_paciente_id_responsable_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.responsable_paciente_id_responsable_seq', 4, true);


--
-- Name: servicio_hospitalizacion_id_servicio_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.servicio_hospitalizacion_id_servicio_seq', 8, true);


--
-- Name: solicitud_cirugia_id_solicitud_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.solicitud_cirugia_id_solicitud_seq', 2, true);


--
-- Name: traslado_id_traslado_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.traslado_id_traslado_seq', 2, true);


--
-- Name: unidad_hospital_id_unidad_hospital_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.unidad_hospital_id_unidad_hospital_seq', 9, true);


--
-- Name: calificacion_enfermero calificacion_enfermero_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calificacion_enfermero
    ADD CONSTRAINT calificacion_enfermero_pkey PRIMARY KEY (id_calificacion);


--
-- Name: calificacion_hospital calificacion_hospital_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calificacion_hospital
    ADD CONSTRAINT calificacion_hospital_pkey PRIMARY KEY (id_calificacion);


--
-- Name: calificacion_medico calificacion_medico_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calificacion_medico
    ADD CONSTRAINT calificacion_medico_pkey PRIMARY KEY (id_calificacion);


--
-- Name: calificacion_personal_encargado calificacion_personal_encargado_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calificacion_personal_encargado
    ADD CONSTRAINT calificacion_personal_encargado_pkey PRIMARY KEY (id_calificacion);


--
-- Name: camilla camilla_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.camilla
    ADD CONSTRAINT camilla_pkey PRIMARY KEY (id_camilla);


--
-- Name: chequeo_preanestesico chequeo_preanestesico_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chequeo_preanestesico
    ADD CONSTRAINT chequeo_preanestesico_pkey PRIMARY KEY (id_chequeo);


--
-- Name: cirugia cirugia_id_solicitud_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cirugia
    ADD CONSTRAINT cirugia_id_solicitud_key UNIQUE (id_solicitud);


--
-- Name: cirugia cirugia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cirugia
    ADD CONSTRAINT cirugia_pkey PRIMARY KEY (id_cirugia);


--
-- Name: cita_programada cita_programada_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cita_programada
    ADD CONSTRAINT cita_programada_pkey PRIMARY KEY (id_cita);


--
-- Name: consentimiento_informado consentimiento_informado_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consentimiento_informado
    ADD CONSTRAINT consentimiento_informado_pkey PRIMARY KEY (id_consentimiento);


--
-- Name: consulta_paciente consulta_paciente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consulta_paciente
    ADD CONSTRAINT consulta_paciente_pkey PRIMARY KEY (id_consulta);


--
-- Name: cuota cuota_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cuota
    ADD CONSTRAINT cuota_pkey PRIMARY KEY (id_cuota);


--
-- Name: departamento departamento_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departamento
    ADD CONSTRAINT departamento_nombre_key UNIQUE (nombre);


--
-- Name: departamento departamento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departamento
    ADD CONSTRAINT departamento_pkey PRIMARY KEY (id_departamento);


--
-- Name: diagnostico_secundario diagnostico_secundario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diagnostico_secundario
    ADD CONSTRAINT diagnostico_secundario_pkey PRIMARY KEY (id_diagnostico_secundario);


--
-- Name: egreso egreso_id_ingreso_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.egreso
    ADD CONSTRAINT egreso_id_ingreso_key UNIQUE (id_ingreso);


--
-- Name: egreso egreso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.egreso
    ADD CONSTRAINT egreso_pkey PRIMARY KEY (id_egreso);


--
-- Name: enfermero enfermero_dpi_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enfermero
    ADD CONSTRAINT enfermero_dpi_key UNIQUE (dpi);


--
-- Name: enfermero enfermero_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enfermero
    ADD CONSTRAINT enfermero_pkey PRIMARY KEY (id_enfermero);


--
-- Name: equipo equipo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipo
    ADD CONSTRAINT equipo_pkey PRIMARY KEY (id_equipo);


--
-- Name: especialidad especialidad_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.especialidad
    ADD CONSTRAINT especialidad_pkey PRIMARY KEY (id_especialidad);


--
-- Name: factura factura_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factura
    ADD CONSTRAINT factura_pkey PRIMARY KEY (id_factura);


--
-- Name: hospital hospital_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hospital
    ADD CONSTRAINT hospital_pkey PRIMARY KEY (id_hospital);


--
-- Name: hospitalizacion_detalle hospitalizacion_detalle_id_ingreso_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hospitalizacion_detalle
    ADD CONSTRAINT hospitalizacion_detalle_id_ingreso_key UNIQUE (id_ingreso);


--
-- Name: hospitalizacion_detalle hospitalizacion_detalle_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hospitalizacion_detalle
    ADD CONSTRAINT hospitalizacion_detalle_pkey PRIMARY KEY (id_hospitalizacion_detalle);


--
-- Name: ingreso ingreso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingreso
    ADD CONSTRAINT ingreso_pkey PRIMARY KEY (id_ingreso);


--
-- Name: instrumento instrumento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instrumento
    ADD CONSTRAINT instrumento_pkey PRIMARY KEY (id_instrumento);


--
-- Name: insumo insumo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.insumo
    ADD CONSTRAINT insumo_pkey PRIMARY KEY (id_insumo);


--
-- Name: insumo_utilizado_cirugia insumo_utilizado_cirugia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.insumo_utilizado_cirugia
    ADD CONSTRAINT insumo_utilizado_cirugia_pkey PRIMARY KEY (id_cirugia, id_insumo);


--
-- Name: medicamento_recetado medicamento_recetado_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medicamento_recetado
    ADD CONSTRAINT medicamento_recetado_pkey PRIMARY KEY (id_medicamento_recetado);


--
-- Name: medico medico_dpi_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT medico_dpi_key UNIQUE (dpi);


--
-- Name: medico medico_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT medico_pkey PRIMARY KEY (id_medico);


--
-- Name: municipio municipio_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.municipio
    ADD CONSTRAINT municipio_pkey PRIMARY KEY (id_municipio);


--
-- Name: paciente paciente_no_expediente_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT paciente_no_expediente_key UNIQUE (no_expediente);


--
-- Name: paciente paciente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT paciente_pkey PRIMARY KEY (id_paciente);


--
-- Name: personal_encargado personal_encargado_dpi_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personal_encargado
    ADD CONSTRAINT personal_encargado_dpi_key UNIQUE (dpi);


--
-- Name: personal_encargado personal_encargado_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personal_encargado
    ADD CONSTRAINT personal_encargado_pkey PRIMARY KEY (id_encargado);


--
-- Name: quirofano quirofano_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quirofano
    ADD CONSTRAINT quirofano_pkey PRIMARY KEY (id_quirofano);


--
-- Name: receta_medica receta_medica_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.receta_medica
    ADD CONSTRAINT receta_medica_pkey PRIMARY KEY (id_receta);


--
-- Name: registro_procedimiento_cirugia registro_procedimiento_cirugia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registro_procedimiento_cirugia
    ADD CONSTRAINT registro_procedimiento_cirugia_pkey PRIMARY KEY (id_registro);


--
-- Name: requerimiento_equipo requerimiento_equipo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimiento_equipo
    ADD CONSTRAINT requerimiento_equipo_pkey PRIMARY KEY (id_solicitud, id_equipo);


--
-- Name: requerimiento_instrumento requerimiento_instrumento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimiento_instrumento
    ADD CONSTRAINT requerimiento_instrumento_pkey PRIMARY KEY (id_solicitud, id_instrumento);


--
-- Name: requerimiento_insumo requerimiento_insumo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimiento_insumo
    ADD CONSTRAINT requerimiento_insumo_pkey PRIMARY KEY (id_solicitud, id_insumo);


--
-- Name: responsable_paciente responsable_paciente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.responsable_paciente
    ADD CONSTRAINT responsable_paciente_pkey PRIMARY KEY (id_responsable);


--
-- Name: servicio_hospitalizacion servicio_hospitalizacion_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.servicio_hospitalizacion
    ADD CONSTRAINT servicio_hospitalizacion_nombre_key UNIQUE (nombre);


--
-- Name: servicio_hospitalizacion servicio_hospitalizacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.servicio_hospitalizacion
    ADD CONSTRAINT servicio_hospitalizacion_pkey PRIMARY KEY (id_servicio);


--
-- Name: solicitud_cirugia solicitud_cirugia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitud_cirugia
    ADD CONSTRAINT solicitud_cirugia_pkey PRIMARY KEY (id_solicitud);


--
-- Name: traslado traslado_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.traslado
    ADD CONSTRAINT traslado_pkey PRIMARY KEY (id_traslado);


--
-- Name: unidad_hospital unidad_hospital_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unidad_hospital
    ADD CONSTRAINT unidad_hospital_pkey PRIMARY KEY (id_unidad_hospital);


--
-- Name: camilla uq_camilla_unidad_numero; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.camilla
    ADD CONSTRAINT uq_camilla_unidad_numero UNIQUE (id_unidad_hospital, numero);


--
-- Name: cuota uq_cuota_factura_numero; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cuota
    ADD CONSTRAINT uq_cuota_factura_numero UNIQUE (id_factura, numero_cuota);


--
-- Name: municipio uq_municipio_nombre_departamento; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.municipio
    ADD CONSTRAINT uq_municipio_nombre_departamento UNIQUE (id_departamento, nombre);


--
-- Name: quirofano uq_quirofano_hospital_numero; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quirofano
    ADD CONSTRAINT uq_quirofano_hospital_numero UNIQUE (id_hospital, numero);


--
-- Name: unidad_hospital uq_unidadhosp_hospital_tipo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unidad_hospital
    ADD CONSTRAINT uq_unidadhosp_hospital_tipo UNIQUE (id_hospital, tipo_unidad);


--
-- Name: calificacion_personal_encargado fk_califenc_encargado; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calificacion_personal_encargado
    ADD CONSTRAINT fk_califenc_encargado FOREIGN KEY (id_encargado) REFERENCES public.personal_encargado(id_encargado) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: calificacion_personal_encargado fk_califenc_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calificacion_personal_encargado
    ADD CONSTRAINT fk_califenc_paciente FOREIGN KEY (id_paciente) REFERENCES public.paciente(id_paciente) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: calificacion_enfermero fk_califenf_enfermero; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calificacion_enfermero
    ADD CONSTRAINT fk_califenf_enfermero FOREIGN KEY (id_enfermero) REFERENCES public.enfermero(id_enfermero) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: calificacion_enfermero fk_califenf_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calificacion_enfermero
    ADD CONSTRAINT fk_califenf_paciente FOREIGN KEY (id_paciente) REFERENCES public.paciente(id_paciente) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: calificacion_hospital fk_califhosp_hospital; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calificacion_hospital
    ADD CONSTRAINT fk_califhosp_hospital FOREIGN KEY (id_hospital) REFERENCES public.hospital(id_hospital) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: calificacion_hospital fk_califhosp_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calificacion_hospital
    ADD CONSTRAINT fk_califhosp_paciente FOREIGN KEY (id_paciente) REFERENCES public.paciente(id_paciente) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: calificacion_medico fk_califmed_medico; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calificacion_medico
    ADD CONSTRAINT fk_califmed_medico FOREIGN KEY (id_medico) REFERENCES public.medico(id_medico) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: calificacion_medico fk_califmed_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.calificacion_medico
    ADD CONSTRAINT fk_califmed_paciente FOREIGN KEY (id_paciente) REFERENCES public.paciente(id_paciente) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: camilla fk_camilla_unidad; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.camilla
    ADD CONSTRAINT fk_camilla_unidad FOREIGN KEY (id_unidad_hospital) REFERENCES public.unidad_hospital(id_unidad_hospital) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: chequeo_preanestesico fk_chequeo_anestesista; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chequeo_preanestesico
    ADD CONSTRAINT fk_chequeo_anestesista FOREIGN KEY (id_anestesista) REFERENCES public.medico(id_medico) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: chequeo_preanestesico fk_chequeo_medico_clasifica; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chequeo_preanestesico
    ADD CONSTRAINT fk_chequeo_medico_clasifica FOREIGN KEY (id_medico_clasifica) REFERENCES public.medico(id_medico) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: chequeo_preanestesico fk_chequeo_solicitud; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chequeo_preanestesico
    ADD CONSTRAINT fk_chequeo_solicitud FOREIGN KEY (id_solicitud) REFERENCES public.solicitud_cirugia(id_solicitud) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: cirugia fk_cirugia_enfermero; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cirugia
    ADD CONSTRAINT fk_cirugia_enfermero FOREIGN KEY (id_enfermero_encargado) REFERENCES public.enfermero(id_enfermero) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: cirugia fk_cirugia_ingreso; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cirugia
    ADD CONSTRAINT fk_cirugia_ingreso FOREIGN KEY (id_ingreso) REFERENCES public.ingreso(id_ingreso) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: cirugia fk_cirugia_quirofano; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cirugia
    ADD CONSTRAINT fk_cirugia_quirofano FOREIGN KEY (id_quirofano) REFERENCES public.quirofano(id_quirofano) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: cirugia fk_cirugia_solicitud; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cirugia
    ADD CONSTRAINT fk_cirugia_solicitud FOREIGN KEY (id_solicitud) REFERENCES public.solicitud_cirugia(id_solicitud) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: cita_programada fk_cita_medico; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cita_programada
    ADD CONSTRAINT fk_cita_medico FOREIGN KEY (id_medico) REFERENCES public.medico(id_medico) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: cita_programada fk_cita_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cita_programada
    ADD CONSTRAINT fk_cita_paciente FOREIGN KEY (id_paciente) REFERENCES public.paciente(id_paciente) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: consentimiento_informado fk_consentimiento_medico; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consentimiento_informado
    ADD CONSTRAINT fk_consentimiento_medico FOREIGN KEY (id_medico) REFERENCES public.medico(id_medico) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: consentimiento_informado fk_consentimiento_solicitud; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consentimiento_informado
    ADD CONSTRAINT fk_consentimiento_solicitud FOREIGN KEY (id_solicitud) REFERENCES public.solicitud_cirugia(id_solicitud) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: consulta_paciente fk_consulta_cita; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consulta_paciente
    ADD CONSTRAINT fk_consulta_cita FOREIGN KEY (id_cita) REFERENCES public.cita_programada(id_cita) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: consulta_paciente fk_consulta_medico; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consulta_paciente
    ADD CONSTRAINT fk_consulta_medico FOREIGN KEY (id_medico) REFERENCES public.medico(id_medico) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: consulta_paciente fk_consulta_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consulta_paciente
    ADD CONSTRAINT fk_consulta_paciente FOREIGN KEY (id_paciente) REFERENCES public.paciente(id_paciente) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: cuota fk_cuota_factura; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cuota
    ADD CONSTRAINT fk_cuota_factura FOREIGN KEY (id_factura) REFERENCES public.factura(id_factura) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: diagnostico_secundario fk_diagsec_egreso; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diagnostico_secundario
    ADD CONSTRAINT fk_diagsec_egreso FOREIGN KEY (id_egreso) REFERENCES public.egreso(id_egreso) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: egreso fk_egreso_ingreso; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.egreso
    ADD CONSTRAINT fk_egreso_ingreso FOREIGN KEY (id_ingreso) REFERENCES public.ingreso(id_ingreso) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: egreso fk_egreso_medico; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.egreso
    ADD CONSTRAINT fk_egreso_medico FOREIGN KEY (id_medico) REFERENCES public.medico(id_medico) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: egreso fk_egreso_traslado; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.egreso
    ADD CONSTRAINT fk_egreso_traslado FOREIGN KEY (id_traslado) REFERENCES public.traslado(id_traslado) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: personal_encargado fk_encargado_hospital; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personal_encargado
    ADD CONSTRAINT fk_encargado_hospital FOREIGN KEY (id_hospital) REFERENCES public.hospital(id_hospital) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: enfermero fk_enfermero_hospital; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enfermero
    ADD CONSTRAINT fk_enfermero_hospital FOREIGN KEY (id_hospital) REFERENCES public.hospital(id_hospital) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: factura fk_factura_consulta; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factura
    ADD CONSTRAINT fk_factura_consulta FOREIGN KEY (id_consulta) REFERENCES public.consulta_paciente(id_consulta) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: factura fk_factura_hospital; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factura
    ADD CONSTRAINT fk_factura_hospital FOREIGN KEY (id_hospital) REFERENCES public.hospital(id_hospital) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: factura fk_factura_ingreso; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factura
    ADD CONSTRAINT fk_factura_ingreso FOREIGN KEY (id_ingreso) REFERENCES public.ingreso(id_ingreso) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: factura fk_factura_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factura
    ADD CONSTRAINT fk_factura_paciente FOREIGN KEY (id_paciente) REFERENCES public.paciente(id_paciente) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: hospitalizacion_detalle fk_hospdet_camilla; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hospitalizacion_detalle
    ADD CONSTRAINT fk_hospdet_camilla FOREIGN KEY (id_camilla) REFERENCES public.camilla(id_camilla) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: hospitalizacion_detalle fk_hospdet_ingreso; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hospitalizacion_detalle
    ADD CONSTRAINT fk_hospdet_ingreso FOREIGN KEY (id_ingreso) REFERENCES public.ingreso(id_ingreso) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: hospitalizacion_detalle fk_hospdet_servicio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hospitalizacion_detalle
    ADD CONSTRAINT fk_hospdet_servicio FOREIGN KEY (id_servicio) REFERENCES public.servicio_hospitalizacion(id_servicio) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: hospital fk_hospital_municipio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hospital
    ADD CONSTRAINT fk_hospital_municipio FOREIGN KEY (id_municipio) REFERENCES public.municipio(id_municipio) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: ingreso fk_ingreso_camilla; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingreso
    ADD CONSTRAINT fk_ingreso_camilla FOREIGN KEY (id_camilla) REFERENCES public.camilla(id_camilla) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: ingreso fk_ingreso_medico; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingreso
    ADD CONSTRAINT fk_ingreso_medico FOREIGN KEY (id_medico) REFERENCES public.medico(id_medico) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: ingreso fk_ingreso_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingreso
    ADD CONSTRAINT fk_ingreso_paciente FOREIGN KEY (id_paciente) REFERENCES public.paciente(id_paciente) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: ingreso fk_ingreso_responsable; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingreso
    ADD CONSTRAINT fk_ingreso_responsable FOREIGN KEY (id_responsable) REFERENCES public.responsable_paciente(id_responsable) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: ingreso fk_ingreso_unidad; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingreso
    ADD CONSTRAINT fk_ingreso_unidad FOREIGN KEY (id_unidad_hospital) REFERENCES public.unidad_hospital(id_unidad_hospital) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: insumo_utilizado_cirugia fk_insumoused_cirugia; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.insumo_utilizado_cirugia
    ADD CONSTRAINT fk_insumoused_cirugia FOREIGN KEY (id_cirugia) REFERENCES public.cirugia(id_cirugia) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: insumo_utilizado_cirugia fk_insumoused_insumo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.insumo_utilizado_cirugia
    ADD CONSTRAINT fk_insumoused_insumo FOREIGN KEY (id_insumo) REFERENCES public.insumo(id_insumo) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: medicamento_recetado fk_medicamento_receta; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medicamento_recetado
    ADD CONSTRAINT fk_medicamento_receta FOREIGN KEY (id_receta) REFERENCES public.receta_medica(id_receta) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: medico fk_medico_especialidad; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT fk_medico_especialidad FOREIGN KEY (id_especialidad) REFERENCES public.especialidad(id_especialidad) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: medico fk_medico_hospital; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT fk_medico_hospital FOREIGN KEY (id_hospital) REFERENCES public.hospital(id_hospital) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: medico fk_medico_municipio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT fk_medico_municipio FOREIGN KEY (id_municipio) REFERENCES public.municipio(id_municipio) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: municipio fk_municipio_departamento; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.municipio
    ADD CONSTRAINT fk_municipio_departamento FOREIGN KEY (id_departamento) REFERENCES public.departamento(id_departamento) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: paciente fk_paciente_municipio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT fk_paciente_municipio FOREIGN KEY (id_municipio) REFERENCES public.municipio(id_municipio) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: quirofano fk_quirofano_hospital; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quirofano
    ADD CONSTRAINT fk_quirofano_hospital FOREIGN KEY (id_hospital) REFERENCES public.hospital(id_hospital) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: receta_medica fk_receta_consulta; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.receta_medica
    ADD CONSTRAINT fk_receta_consulta FOREIGN KEY (id_consulta) REFERENCES public.consulta_paciente(id_consulta) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: receta_medica fk_receta_hospital; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.receta_medica
    ADD CONSTRAINT fk_receta_hospital FOREIGN KEY (id_hospital) REFERENCES public.hospital(id_hospital) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: registro_procedimiento_cirugia fk_registro_cirugia; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registro_procedimiento_cirugia
    ADD CONSTRAINT fk_registro_cirugia FOREIGN KEY (id_cirugia) REFERENCES public.cirugia(id_cirugia) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: registro_procedimiento_cirugia fk_registro_enfermero; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registro_procedimiento_cirugia
    ADD CONSTRAINT fk_registro_enfermero FOREIGN KEY (id_enfermero) REFERENCES public.enfermero(id_enfermero) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: requerimiento_equipo fk_reqequipo_equipo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimiento_equipo
    ADD CONSTRAINT fk_reqequipo_equipo FOREIGN KEY (id_equipo) REFERENCES public.equipo(id_equipo) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: requerimiento_equipo fk_reqequipo_solicitud; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimiento_equipo
    ADD CONSTRAINT fk_reqequipo_solicitud FOREIGN KEY (id_solicitud) REFERENCES public.solicitud_cirugia(id_solicitud) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: requerimiento_instrumento fk_reqinstr_instrumento; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimiento_instrumento
    ADD CONSTRAINT fk_reqinstr_instrumento FOREIGN KEY (id_instrumento) REFERENCES public.instrumento(id_instrumento) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: requerimiento_instrumento fk_reqinstr_solicitud; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimiento_instrumento
    ADD CONSTRAINT fk_reqinstr_solicitud FOREIGN KEY (id_solicitud) REFERENCES public.solicitud_cirugia(id_solicitud) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: requerimiento_insumo fk_reqinsumo_insumo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimiento_insumo
    ADD CONSTRAINT fk_reqinsumo_insumo FOREIGN KEY (id_insumo) REFERENCES public.insumo(id_insumo) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: requerimiento_insumo fk_reqinsumo_solicitud; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimiento_insumo
    ADD CONSTRAINT fk_reqinsumo_solicitud FOREIGN KEY (id_solicitud) REFERENCES public.solicitud_cirugia(id_solicitud) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: responsable_paciente fk_responsable_municipio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.responsable_paciente
    ADD CONSTRAINT fk_responsable_municipio FOREIGN KEY (id_municipio) REFERENCES public.municipio(id_municipio) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: responsable_paciente fk_responsable_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.responsable_paciente
    ADD CONSTRAINT fk_responsable_paciente FOREIGN KEY (id_paciente) REFERENCES public.paciente(id_paciente) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: solicitud_cirugia fk_solicitud_cirujano; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitud_cirugia
    ADD CONSTRAINT fk_solicitud_cirujano FOREIGN KEY (id_cirujano) REFERENCES public.medico(id_medico) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: solicitud_cirugia fk_solicitud_hospital; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitud_cirugia
    ADD CONSTRAINT fk_solicitud_hospital FOREIGN KEY (id_hospital) REFERENCES public.hospital(id_hospital) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: solicitud_cirugia fk_solicitud_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitud_cirugia
    ADD CONSTRAINT fk_solicitud_paciente FOREIGN KEY (id_paciente) REFERENCES public.paciente(id_paciente) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: solicitud_cirugia fk_solicitud_quirofano; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitud_cirugia
    ADD CONSTRAINT fk_solicitud_quirofano FOREIGN KEY (id_quirofano) REFERENCES public.quirofano(id_quirofano) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: traslado fk_traslado_medico; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.traslado
    ADD CONSTRAINT fk_traslado_medico FOREIGN KEY (id_medico_indica) REFERENCES public.medico(id_medico) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: traslado fk_traslado_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.traslado
    ADD CONSTRAINT fk_traslado_paciente FOREIGN KEY (id_paciente) REFERENCES public.paciente(id_paciente) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: traslado fk_traslado_unidad_destino; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.traslado
    ADD CONSTRAINT fk_traslado_unidad_destino FOREIGN KEY (id_unidad_destino) REFERENCES public.unidad_hospital(id_unidad_hospital) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: traslado fk_traslado_unidad_origen; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.traslado
    ADD CONSTRAINT fk_traslado_unidad_origen FOREIGN KEY (id_unidad_origen) REFERENCES public.unidad_hospital(id_unidad_hospital) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: unidad_hospital fk_unidadhosp_hospital; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unidad_hospital
    ADD CONSTRAINT fk_unidadhosp_hospital FOREIGN KEY (id_hospital) REFERENCES public.hospital(id_hospital) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict Zp7AiKoeyZRUtW1PPIzGF9taOsDJeVF9uB1dYhfSYbP5WFeUDRVpbKOAN13ffe3

