-- Nucleo - catalogos de ubicacion, hospitales y personas
-- Restricciones 
--   FK obligatoria -> entidad maestra (paciente/medico/hospital): RESTRICT en DELETE
--   FK obligatoria -> entidad "evento" de la que el hijo es detalle:     CASCADE en DELETE
--   FK opcional (NULL permitido):                                       SET NULL en DELETE
--   UPDATE siempre CASCADE (las PK son subrogadas/seriales, no cambian, pero se deja explicito)

CREATE TABLE departamento (
    id_departamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(100) NOT NULL UNIQUE
);
COMMENT ON TABLE departamento IS 'Catalogo de departamentos de Guatemala, usado en toda direccion registrada';

CREATE TABLE municipio (
    id_municipio     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_departamento  INTEGER NOT NULL
        CONSTRAINT fk_municipio_departamento REFERENCES departamento(id_departamento)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    nombre           VARCHAR(100) NOT NULL,
    CONSTRAINT uq_municipio_nombre_departamento UNIQUE (id_departamento, nombre)
);
COMMENT ON TABLE municipio IS 'Catalogo de municipios; cada uno pertenece a un unico departamento';

CREATE TABLE especialidad (
    id_especialidad  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(100) NOT NULL,
    categoria        VARCHAR(25) NOT NULL
        CONSTRAINT chk_especialidad_categoria CHECK (categoria IN ('Consulta_Emergencia', 'Cirugia', 'Hospitalizacion')) -- valida el ambito donde se ofrece la especialidad/servicio
);
COMMENT ON TABLE especialidad IS 'Catalogo unico de especialidades/servicios medicos ofrecidos por unidad';

CREATE TABLE hospital (
    id_hospital      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(150) NOT NULL,
    direccion        VARCHAR(200) NOT NULL,
    id_municipio     INTEGER NOT NULL
        CONSTRAINT fk_hospital_municipio REFERENCES municipio(id_municipio)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    telefono         VARCHAR(20)
);
COMMENT ON TABLE hospital IS 'Cada uno de los hospitales que conforman la cadena Hospitales de Occidente';

CREATE TABLE paciente (
    id_paciente        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    no_expediente      VARCHAR(20) NOT NULL UNIQUE,
    nombres            VARCHAR(100) NOT NULL,
    apellidos          VARCHAR(100) NOT NULL,
    sexo               CHAR(1) NOT NULL
        CONSTRAINT chk_paciente_sexo CHECK (sexo IN ('M', 'F')), -- valida sexo Masculino/Femenino
    fecha_nacimiento   DATE NOT NULL
        CONSTRAINT chk_paciente_fecha_nacimiento CHECK (fecha_nacimiento <= CURRENT_DATE), -- valida que no haya nacimientos futuros (rango de edad valido)
    id_municipio       INTEGER NOT NULL
        CONSTRAINT fk_paciente_municipio REFERENCES municipio(id_municipio)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    area               VARCHAR(10) NOT NULL
        CONSTRAINT chk_paciente_area CHECK (area IN ('Urbana', 'Rural')), -- valida area de residencia
    dpi                VARCHAR(13),
    telefono           VARCHAR(20),
    no_seguro_social   VARCHAR(20)
);
COMMENT ON TABLE paciente IS 'Paciente atendido en cualquier unidad de cualquier hospital de la cadena';

CREATE TABLE responsable_paciente (
    id_responsable   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente      INTEGER NOT NULL
        CONSTRAINT fk_responsable_paciente REFERENCES paciente(id_paciente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    nombre           VARCHAR(150) NOT NULL,
    parentesco       VARCHAR(50) NOT NULL,
    dpi              VARCHAR(13),
    telefono         VARCHAR(20),
    id_municipio     INTEGER
        CONSTRAINT fk_responsable_municipio REFERENCES municipio(id_municipio)
        ON DELETE SET NULL ON UPDATE CASCADE,
    area             VARCHAR(10)
        CONSTRAINT chk_responsable_area CHECK (area IS NULL OR area IN ('Urbana', 'Rural')) -- valida area de residencia si se registra
);
COMMENT ON TABLE responsable_paciente IS 'Familiar o responsable del paciente registrado en la ficha de ingreso (no es personal del hospital)';

CREATE TABLE medico (
    id_medico        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(150) NOT NULL,
    dpi              VARCHAR(13) NOT NULL UNIQUE,
    id_especialidad  INTEGER NOT NULL
        CONSTRAINT fk_medico_especialidad REFERENCES especialidad(id_especialidad)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    tipo_medico      VARCHAR(20) NOT NULL
        CONSTRAINT chk_medico_tipo CHECK (tipo_medico IN ('Residente', 'Interno', 'Externo')), -- valida el tipo de vinculacion del medico (relevante en Cirugia)
    id_hospital      INTEGER NOT NULL
        CONSTRAINT fk_medico_hospital REFERENCES hospital(id_hospital)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    telefono         VARCHAR(20),
    id_municipio     INTEGER
        CONSTRAINT fk_medico_municipio REFERENCES municipio(id_municipio)
        ON DELETE SET NULL ON UPDATE CASCADE,
    area             VARCHAR(10)
        CONSTRAINT chk_medico_area CHECK (area IS NULL OR area IN ('Urbana', 'Rural'))
);
COMMENT ON TABLE medico IS 'Medico que atiende en un hospital, en alguna de sus unidades';

CREATE TABLE enfermero (
    id_enfermero     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(150) NOT NULL,
    dpi              VARCHAR(13) NOT NULL UNIQUE,
    tipo_enfermero   VARCHAR(20) NOT NULL
        CONSTRAINT chk_enfermero_tipo CHECK (tipo_enfermero IN ('Registrado', 'Practicante')), -- valida el tipo de enfermero
    id_hospital      INTEGER NOT NULL
        CONSTRAINT fk_enfermero_hospital REFERENCES hospital(id_hospital)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
COMMENT ON TABLE enfermero IS 'Enfermero registrado o practicante asignado a un hospital';

CREATE TABLE personal_encargado (
    id_encargado     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(150) NOT NULL,
    dpi              VARCHAR(13) NOT NULL UNIQUE,
    puesto           VARCHAR(100) NOT NULL,
    id_hospital      INTEGER NOT NULL
        CONSTRAINT fk_encargado_hospital REFERENCES hospital(id_hospital)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    telefono         VARCHAR(20)
);
COMMENT ON TABLE personal_encargado IS 'Personal administrativo/encargado de un hospital, sujeto de calificacion de calidad (distinto del responsable del paciente)';
