-- DDL 02: Consulta Externa

CREATE TABLE cita_programada (
    id_cita        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente    INTEGER NOT NULL
        CONSTRAINT fk_cita_paciente REFERENCES paciente(id_paciente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_medico      INTEGER NOT NULL
        CONSTRAINT fk_cita_medico REFERENCES medico(id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    fecha          DATE NOT NULL,
    hora           TIME NOT NULL,
    estado         VARCHAR(15) NOT NULL DEFAULT 'Programada'
        CONSTRAINT chk_cita_estado CHECK (estado IN ('Programada', 'Realizada', 'Reprogramada', 'Cancelada')), -- valida el estado de la cita
    consultorio    VARCHAR(20)
);
COMMENT ON TABLE cita_programada IS 'Cita de consulta externa asignada via telefono, correo o recepcion general';

CREATE TABLE consulta_paciente (
    id_consulta            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente            INTEGER NOT NULL
        CONSTRAINT fk_consulta_paciente REFERENCES paciente(id_paciente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_medico              INTEGER NOT NULL
        CONSTRAINT fk_consulta_medico REFERENCES medico(id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    fecha                  DATE NOT NULL,
    tipo_consulta          VARCHAR(15) NOT NULL
        CONSTRAINT chk_consulta_tipo CHECK (tipo_consulta IN ('Primera', 'Reconsulta')), -- valida si es primera consulta o reconsulta (define el % de costo)
    referido_institucion   BOOLEAN NOT NULL DEFAULT FALSE,
    id_cita                INTEGER
        CONSTRAINT fk_consulta_cita REFERENCES cita_programada(id_cita)
        ON DELETE SET NULL ON UPDATE CASCADE,
    diagnostico            TEXT,
    notas                  TEXT
);
COMMENT ON TABLE consulta_paciente IS 'Ficha de consulta realizada en Consulta Externa (programada o de paciente referido)';

CREATE TABLE receta_medica (
    id_receta        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_consulta      INTEGER NOT NULL
        CONSTRAINT fk_receta_consulta REFERENCES consulta_paciente(id_consulta)
        ON DELETE CASCADE ON UPDATE CASCADE,
    fecha            DATE NOT NULL,
    id_hospital      INTEGER NOT NULL
        CONSTRAINT fk_receta_hospital REFERENCES hospital(id_hospital)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    proxima_cita     DATE,
    numero_clinica   VARCHAR(20)
);
COMMENT ON TABLE receta_medica IS 'Receta medica emitida al finalizar una consulta de Consulta Externa';

CREATE TABLE medicamento_recetado (
    id_medicamento_recetado  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_receta                INTEGER NOT NULL
        CONSTRAINT fk_medicamento_receta REFERENCES receta_medica(id_receta)
        ON DELETE CASCADE ON UPDATE CASCADE,
    nombre                   VARCHAR(150) NOT NULL,
    dosis                    VARCHAR(100) NOT NULL,
    duracion                 VARCHAR(100) NOT NULL
);
COMMENT ON TABLE medicamento_recetado IS 'Medicamento individual prescrito dentro de una receta medica';
