-- DDL 03: Ingreso / Egreso / Traslado - comun a Emergencias, Cirugia y Hospitalizacion

CREATE TABLE unidad_hospital (
    id_unidad_hospital  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hospital         INTEGER NOT NULL
        CONSTRAINT fk_unidadhosp_hospital REFERENCES hospital(id_hospital)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    tipo_unidad         VARCHAR(20) NOT NULL
        CONSTRAINT chk_unidadhosp_tipo CHECK (tipo_unidad IN ('Emergencias', 'Cirugia', 'Hospitalizacion')), -- valida la unidad medica del hospital
    CONSTRAINT uq_unidadhosp_hospital_tipo UNIQUE (id_hospital, tipo_unidad)
);
COMMENT ON TABLE unidad_hospital IS 'Unidad medica (Emergencias/Cirugia/Hospitalizacion) concreta de un hospital especifico';

CREATE TABLE camilla (
    id_camilla          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad_hospital  INTEGER NOT NULL
        CONSTRAINT fk_camilla_unidad REFERENCES unidad_hospital(id_unidad_hospital)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    numero              INTEGER NOT NULL,
    estado              VARCHAR(10) NOT NULL DEFAULT 'Libre'
        CONSTRAINT chk_camilla_estado CHECK (estado IN ('Libre', 'Ocupada')), -- valida disponibilidad de la camilla
    CONSTRAINT uq_camilla_unidad_numero UNIQUE (id_unidad_hospital, numero)
);
COMMENT ON TABLE camilla IS 'Camilla habilitada dentro de una unidad de Emergencias u Hospitalizacion';

CREATE TABLE ingreso (
    id_ingreso              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente             INTEGER NOT NULL
        CONSTRAINT fk_ingreso_paciente REFERENCES paciente(id_paciente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_unidad_hospital      INTEGER NOT NULL
        CONSTRAINT fk_ingreso_unidad REFERENCES unidad_hospital(id_unidad_hospital)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_medico               INTEGER NOT NULL
        CONSTRAINT fk_ingreso_medico REFERENCES medico(id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    fecha_hora              TIMESTAMP NOT NULL,
    motivo_ingreso          TEXT NOT NULL,
    id_responsable          INTEGER
        CONSTRAINT fk_ingreso_responsable REFERENCES responsable_paciente(id_responsable)
        ON DELETE SET NULL ON UPDATE CASCADE,
    id_camilla              INTEGER
        CONSTRAINT fk_ingreso_camilla REFERENCES camilla(id_camilla)
        ON DELETE SET NULL ON UPDATE CASCADE,
    diagnostico_presuntivo  TEXT
);
COMMENT ON TABLE ingreso IS 'Ficha de ingreso: registra el estado del paciente al ingresar a Emergencias, Cirugia u Hospitalizacion';

CREATE TABLE traslado (
    id_traslado         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente         INTEGER NOT NULL
        CONSTRAINT fk_traslado_paciente REFERENCES paciente(id_paciente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_medico_indica    INTEGER NOT NULL
        CONSTRAINT fk_traslado_medico REFERENCES medico(id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    fecha_hora          TIMESTAMP NOT NULL,
    id_unidad_destino   INTEGER NOT NULL
        CONSTRAINT fk_traslado_unidad_destino REFERENCES unidad_hospital(id_unidad_hospital)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    interno_destino     BOOLEAN NOT NULL,
    id_unidad_origen    INTEGER
        CONSTRAINT fk_traslado_unidad_origen REFERENCES unidad_hospital(id_unidad_hospital)
        ON DELETE SET NULL ON UPDATE CASCADE,
    interno_origen      BOOLEAN
);
COMMENT ON TABLE traslado IS 'Ficha de traslado de un paciente entre unidades (o desde/hacia otra institucion)';

CREATE TABLE egreso (
    id_egreso                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ingreso                   INTEGER NOT NULL UNIQUE
        CONSTRAINT fk_egreso_ingreso REFERENCES ingreso(id_ingreso)
        ON DELETE CASCADE ON UPDATE CASCADE,
    id_medico                    INTEGER NOT NULL
        CONSTRAINT fk_egreso_medico REFERENCES medico(id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    fecha_hora                    TIMESTAMP NOT NULL,
    diagnostico_principal         TEXT NOT NULL,
    motivo_egreso                 TEXT NOT NULL,
    codigo_egreso                 VARCHAR(10) NOT NULL
        CONSTRAINT chk_egreso_codigo CHECK (codigo_egreso IN ('Vivo', 'Muerto', 'Embarazo', 'Parto')), -- valida el codigo de egreso
    egreso_sin_consentimiento     BOOLEAN NOT NULL DEFAULT FALSE,
    motivo_sin_consentimiento     TEXT
        CONSTRAINT chk_egreso_motivo_consentimiento CHECK (
            (egreso_sin_consentimiento = FALSE AND motivo_sin_consentimiento IS NULL)
            OR (egreso_sin_consentimiento = TRUE AND motivo_sin_consentimiento IS NOT NULL)
        ), -- valida que el motivo se registre solo cuando el egreso fue sin consentimiento
    id_traslado                   INTEGER
        CONSTRAINT fk_egreso_traslado REFERENCES traslado(id_traslado)
        ON DELETE SET NULL ON UPDATE CASCADE,
    dias_hospitalizado            INTEGER
        CONSTRAINT chk_egreso_dias CHECK (dias_hospitalizado IS NULL OR dias_hospitalizado >= 0), -- valida que los dias hospitalizado no sean negativos
    referido_otro_hospital        VARCHAR(150)
);
COMMENT ON TABLE egreso IS 'Ficha de egreso: cierra un ingreso, sea por alta, hospitalizacion, cirugia o defuncion';

CREATE TABLE diagnostico_secundario (
    id_diagnostico_secundario  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_egreso                  INTEGER NOT NULL
        CONSTRAINT fk_diagsec_egreso REFERENCES egreso(id_egreso)
        ON DELETE CASCADE ON UPDATE CASCADE,
    descripcion                 TEXT NOT NULL
);
COMMENT ON TABLE diagnostico_secundario IS 'Diagnostico secundario adicional registrado en una ficha de egreso (relacion 1:N)';
