-- DDL 04: Cirugia

CREATE TABLE insumo (
    id_insumo    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(150) NOT NULL,
    material     VARCHAR(100) NOT NULL,
    tipo         VARCHAR(15) NOT NULL
        CONSTRAINT chk_insumo_tipo CHECK (tipo IN ('Medico', 'Quirurgico', 'Otro')), -- valida el tipo de insumo
    descripcion  TEXT
);
COMMENT ON TABLE insumo IS 'Catalogo de insumos que se pueden requerir y utilizar en una cirugia';

CREATE TABLE instrumento (
    id_instrumento  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(150) NOT NULL,
    tipo            VARCHAR(15) NOT NULL
        CONSTRAINT chk_instrumento_tipo CHECK (tipo IN ('Medico', 'Quirurgico', 'Otro')), -- valida el tipo de instrumento
    funcion         VARCHAR(20) NOT NULL
        CONSTRAINT chk_instrumento_funcion CHECK (funcion IN ('Corte', 'Contencion', 'Hemostatica', 'Retractor', 'Accesorio', 'Implante', 'Otro')), -- valida la funcion del instrumento
    descripcion     TEXT
);
COMMENT ON TABLE instrumento IS 'Catalogo de instrumental quirurgico requerido en una cirugia';

CREATE TABLE equipo (
    id_equipo    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(150) NOT NULL,
    tipo         VARCHAR(15) NOT NULL
        CONSTRAINT chk_equipo_tipo CHECK (tipo IN ('Medico', 'Quirurgico', 'Otro')), -- valida el tipo de equipo
    funcion      VARCHAR(20) NOT NULL
        CONSTRAINT chk_equipo_funcion CHECK (funcion IN ('Exploracion', 'Diagnostico', 'Tratamiento', 'Rehabilitacion', 'Otro')), -- valida la funcion del equipo
    descripcion  TEXT
);
COMMENT ON TABLE equipo IS 'Catalogo de equipos medicos requeridos en una cirugia';

CREATE TABLE quirofano (
    id_quirofano  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hospital   INTEGER NOT NULL
        CONSTRAINT fk_quirofano_hospital REFERENCES hospital(id_hospital)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    numero        INTEGER NOT NULL,
    estado        VARCHAR(10) NOT NULL DEFAULT 'Libre'
        CONSTRAINT chk_quirofano_estado CHECK (estado IN ('Libre', 'Ocupado')), -- valida disponibilidad del quirofano
    CONSTRAINT uq_quirofano_hospital_numero UNIQUE (id_hospital, numero)
);
COMMENT ON TABLE quirofano IS 'Quirofano habilitado de un hospital (cada hospital cuenta con varios)';

CREATE TABLE solicitud_cirugia (
    id_solicitud           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente            INTEGER NOT NULL
        CONSTRAINT fk_solicitud_paciente REFERENCES paciente(id_paciente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_cirujano            INTEGER NOT NULL
        CONSTRAINT fk_solicitud_cirujano REFERENCES medico(id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    caracter               VARCHAR(15) NOT NULL
        CONSTRAINT chk_solicitud_caracter CHECK (caracter IN ('Urgente', 'Programado')), -- valida el caracter de la cirugia solicitada
    tipo_procedimiento     VARCHAR(150) NOT NULL,
    fecha_hora_solicitud   TIMESTAMP NOT NULL,
    estado                 VARCHAR(15) NOT NULL DEFAULT 'Pendiente'
        CONSTRAINT chk_solicitud_estado CHECK (estado IN ('Pendiente', 'Aprobada', 'Rechazada')), -- valida el estado de revision del comite medico
    id_hospital            INTEGER NOT NULL
        CONSTRAINT fk_solicitud_hospital REFERENCES hospital(id_hospital)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    historia_clinica       TEXT,
    tiempo_estimado        INTERVAL,
    tipo_anestesia         VARCHAR(100),
    motivo_rechazo         TEXT
        CONSTRAINT chk_solicitud_motivo_rechazo CHECK (
            (estado = 'Rechazada' AND motivo_rechazo IS NOT NULL)
            OR (estado <> 'Rechazada' AND motivo_rechazo IS NULL)
        ), -- valida que el motivo de rechazo solo se registre cuando la solicitud fue rechazada (asi se resuelve la "base de cirugias rechazadas" como filtro)
    id_quirofano           INTEGER
        CONSTRAINT fk_solicitud_quirofano REFERENCES quirofano(id_quirofano)
        ON DELETE SET NULL ON UPDATE CASCADE,
    fecha_hora_agendada    TIMESTAMP
);
COMMENT ON TABLE solicitud_cirugia IS 'Agendamiento quirurgico solicitado por el cirujano, revisado por el comite medico';

CREATE TABLE requerimiento_insumo (
    id_solicitud  INTEGER NOT NULL
        CONSTRAINT fk_reqinsumo_solicitud REFERENCES solicitud_cirugia(id_solicitud)
        ON DELETE CASCADE ON UPDATE CASCADE,
    id_insumo     INTEGER NOT NULL
        CONSTRAINT fk_reqinsumo_insumo REFERENCES insumo(id_insumo)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    cantidad      INTEGER NOT NULL
        CONSTRAINT chk_reqinsumo_cantidad CHECK (cantidad > 0), -- valida que la cantidad requerida sea positiva
    PRIMARY KEY (id_solicitud, id_insumo)
);
COMMENT ON TABLE requerimiento_insumo IS 'Resuelve la relacion N:M entre solicitud_cirugia e insumo (llave primaria compuesta)';

CREATE TABLE requerimiento_instrumento (
    id_solicitud    INTEGER NOT NULL
        CONSTRAINT fk_reqinstr_solicitud REFERENCES solicitud_cirugia(id_solicitud)
        ON DELETE CASCADE ON UPDATE CASCADE,
    id_instrumento  INTEGER NOT NULL
        CONSTRAINT fk_reqinstr_instrumento REFERENCES instrumento(id_instrumento)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    cantidad        INTEGER NOT NULL
        CONSTRAINT chk_reqinstr_cantidad CHECK (cantidad > 0), -- valida que la cantidad requerida sea positiva
    PRIMARY KEY (id_solicitud, id_instrumento)
);
COMMENT ON TABLE requerimiento_instrumento IS 'Resuelve la relacion N:M entre solicitud_cirugia e instrumento (llave primaria compuesta)';

CREATE TABLE requerimiento_equipo (
    id_solicitud  INTEGER NOT NULL
        CONSTRAINT fk_reqequipo_solicitud REFERENCES solicitud_cirugia(id_solicitud)
        ON DELETE CASCADE ON UPDATE CASCADE,
    id_equipo     INTEGER NOT NULL
        CONSTRAINT fk_reqequipo_equipo REFERENCES equipo(id_equipo)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    cantidad      INTEGER NOT NULL
        CONSTRAINT chk_reqequipo_cantidad CHECK (cantidad > 0), -- valida que la cantidad requerida sea positiva
    PRIMARY KEY (id_solicitud, id_equipo)
);
COMMENT ON TABLE requerimiento_equipo IS 'Resuelve la relacion N:M entre solicitud_cirugia y equipo (llave primaria compuesta)';

CREATE TABLE consentimiento_informado (
    id_consentimiento     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitud          INTEGER NOT NULL
        CONSTRAINT fk_consentimiento_solicitud REFERENCES solicitud_cirugia(id_solicitud)
        ON DELETE CASCADE ON UPDATE CASCADE,
    nombre_procedimiento  VARCHAR(150) NOT NULL,
    objetivo              TEXT NOT NULL,
    id_medico             INTEGER NOT NULL
        CONSTRAINT fk_consentimiento_medico REFERENCES medico(id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    firma_paciente        VARCHAR(150) NOT NULL,
    fecha                 DATE NOT NULL,
    caracteristicas       TEXT,
    riesgos               TEXT
);
COMMENT ON TABLE consentimiento_informado IS 'Consentimiento informado firmado antes de la cirugia (paciente, familiar, tutor o representante)';

CREATE TABLE chequeo_preanestesico (
    id_chequeo            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitud          INTEGER NOT NULL
        CONSTRAINT fk_chequeo_solicitud REFERENCES solicitud_cirugia(id_solicitud)
        ON DELETE CASCADE ON UPDATE CASCADE,
    clasificacion_asa     VARCHAR(3) NOT NULL
        CONSTRAINT chk_chequeo_asa CHECK (clasificacion_asa IN ('I', 'II', 'III', 'IV', 'V', 'VI')), -- valida la clasificacion de riesgo anestesico ASA
    id_medico_clasifica   INTEGER NOT NULL
        CONSTRAINT fk_chequeo_medico_clasifica REFERENCES medico(id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_anestesista        INTEGER NOT NULL
        CONSTRAINT fk_chequeo_anestesista REFERENCES medico(id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    plan_anestesia        TEXT
);
COMMENT ON TABLE chequeo_preanestesico IS 'Chequeo preanestesico previo a la cirugia: clasificacion ASA y plan de anestesia';

CREATE TABLE cirugia (
    id_cirugia               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitud             INTEGER NOT NULL UNIQUE
        CONSTRAINT fk_cirugia_solicitud REFERENCES solicitud_cirugia(id_solicitud)
        ON DELETE CASCADE ON UPDATE CASCADE,
    id_ingreso               INTEGER NOT NULL
        CONSTRAINT fk_cirugia_ingreso REFERENCES ingreso(id_ingreso)
        ON DELETE CASCADE ON UPDATE CASCADE,
    id_quirofano             INTEGER NOT NULL
        CONSTRAINT fk_cirugia_quirofano REFERENCES quirofano(id_quirofano)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_enfermero_encargado   INTEGER NOT NULL
        CONSTRAINT fk_cirugia_enfermero REFERENCES enfermero(id_enfermero)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    fecha_hora_inicio        TIMESTAMP NOT NULL,
    fecha_hora_fin           TIMESTAMP
        CONSTRAINT chk_cirugia_fin_posterior CHECK (fecha_hora_fin IS NULL OR fecha_hora_fin >= fecha_hora_inicio), -- valida que el fin no sea anterior al inicio
    costo                    NUMERIC(10, 2)
        CONSTRAINT chk_cirugia_costo CHECK (costo IS NULL OR costo >= 0) -- valida que el costo no sea negativo
);
COMMENT ON TABLE cirugia IS 'Evento intraoperatorio real: ejecucion de una solicitud de cirugia aprobada';

CREATE TABLE insumo_utilizado_cirugia (
    id_cirugia  INTEGER NOT NULL
        CONSTRAINT fk_insumoused_cirugia REFERENCES cirugia(id_cirugia)
        ON DELETE CASCADE ON UPDATE CASCADE,
    id_insumo   INTEGER NOT NULL
        CONSTRAINT fk_insumoused_insumo REFERENCES insumo(id_insumo)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    cantidad    INTEGER NOT NULL
        CONSTRAINT chk_insumoused_cantidad CHECK (cantidad > 0), -- valida que la cantidad utilizada sea positiva
    PRIMARY KEY (id_cirugia, id_insumo)
);
COMMENT ON TABLE insumo_utilizado_cirugia IS 'Insumos efectivamente utilizados durante una cirugia (base para el calculo del costo)';

CREATE TABLE registro_procedimiento_cirugia (
    id_registro     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cirugia      INTEGER NOT NULL
        CONSTRAINT fk_registro_cirugia REFERENCES cirugia(id_cirugia)
        ON DELETE CASCADE ON UPDATE CASCADE,
    etapa           VARCHAR(15) NOT NULL
        CONSTRAINT chk_registro_etapa CHECK (etapa IN ('Preoperatorio', 'Intraoperatorio', 'Postoperatorio')), -- valida la etapa quirurgica del registro
    procedimiento   VARCHAR(150) NOT NULL,
    resultado       VARCHAR(25) NOT NULL
        CONSTRAINT chk_registro_resultado CHECK (resultado IN ('Aceptable', 'Medianamente aceptable', 'No aceptable', 'Exito', 'Falla')), -- valida el resultado registrado (escala segun el checklist del item)
    hora_registro   TIMESTAMP NOT NULL,
    id_enfermero    INTEGER NOT NULL
        CONSTRAINT fk_registro_enfermero REFERENCES enfermero(id_enfermero)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    descripcion     TEXT
);
COMMENT ON TABLE registro_procedimiento_cirugia IS 'Registro normalizado de todos los checklists de la cirugia (preoperatorio, chequeo en quirofano, pausa quirurgica, cuidados intraoperatorios, salida, recuperacion, traslado seguro)';
