-- DDL 05: Hospitalizacion, Facturacion y Calificaciones

CREATE TABLE servicio_hospitalizacion (
    id_servicio  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(100) NOT NULL UNIQUE
);
COMMENT ON TABLE servicio_hospitalizacion IS 'Catalogo de servicios de Hospitalizacion (Hematologia, Medicina interna, Neumologia, Oncologia, Ortopedia, Pediatria, cuidados intermedios, cuidado critico)';

CREATE TABLE hospitalizacion_detalle (
    id_hospitalizacion_detalle  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ingreso                  INTEGER NOT NULL UNIQUE
        CONSTRAINT fk_hospdet_ingreso REFERENCES ingreso(id_ingreso)
        ON DELETE CASCADE ON UPDATE CASCADE,
    id_servicio                 INTEGER NOT NULL
        CONSTRAINT fk_hospdet_servicio REFERENCES servicio_hospitalizacion(id_servicio)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_camilla                  INTEGER NOT NULL
        CONSTRAINT fk_hospdet_camilla REFERENCES camilla(id_camilla)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    costo_dia                   NUMERIC(10, 2)
        CONSTRAINT chk_hospdet_costo_dia CHECK (costo_dia IS NULL OR costo_dia >= 0), -- valida que el costo por dia no sea negativo
    dias                        INTEGER
        CONSTRAINT chk_hospdet_dias CHECK (dias IS NULL OR dias >= 0) -- valida que los dias internado no sean negativos
);
COMMENT ON TABLE hospitalizacion_detalle IS 'Detalle de la estadia de hospitalizacion asociada a un ingreso (servicio, camilla y costo)';

CREATE TABLE factura (
    id_factura     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hospital    INTEGER NOT NULL
        CONSTRAINT fk_factura_hospital REFERENCES hospital(id_hospital)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_paciente    INTEGER NOT NULL
        CONSTRAINT fk_factura_paciente REFERENCES paciente(id_paciente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    fecha          DATE NOT NULL,
    descripcion    TEXT NOT NULL,
    monto          NUMERIC(10, 2) NOT NULL
        CONSTRAINT chk_factura_monto CHECK (monto > 0), -- valida que el monto facturado sea positivo
    id_consulta    INTEGER
        CONSTRAINT fk_factura_consulta REFERENCES consulta_paciente(id_consulta)
        ON DELETE SET NULL ON UPDATE CASCADE,
    id_ingreso     INTEGER
        CONSTRAINT fk_factura_ingreso REFERENCES ingreso(id_ingreso)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT chk_factura_origen_exclusivo CHECK (
        (id_consulta IS NOT NULL AND id_ingreso IS NULL)
        OR (id_consulta IS NULL AND id_ingreso IS NOT NULL)
    ) -- valida el arco exclusivo: la factura viene de una consulta externa O de un ingreso, nunca ambas ni ninguna
);
COMMENT ON TABLE factura IS 'Factura emitida al cancelar el servicio, ya sea de Consulta Externa o de una unidad de internamiento';

CREATE TABLE cuota (
    id_cuota       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_factura     INTEGER NOT NULL
        CONSTRAINT fk_cuota_factura REFERENCES factura(id_factura)
        ON DELETE CASCADE ON UPDATE CASCADE,
    numero_cuota   INTEGER NOT NULL
        CONSTRAINT chk_cuota_numero CHECK (numero_cuota BETWEEN 1 AND 12), -- valida que el pago sea de 1 a 12 cuotas mensuales
    monto          NUMERIC(10, 2) NOT NULL
        CONSTRAINT chk_cuota_monto CHECK (monto > 0), -- valida que el monto de la cuota sea positivo
    fecha_pago     DATE,
    CONSTRAINT uq_cuota_factura_numero UNIQUE (id_factura, numero_cuota)
);
COMMENT ON TABLE cuota IS 'Cuota mensual de pago de una factura (hasta 12 pagos)';

CREATE TABLE calificacion_hospital (
    id_calificacion  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hospital      INTEGER NOT NULL
        CONSTRAINT fk_califhosp_hospital REFERENCES hospital(id_hospital)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    puntaje          SMALLINT NOT NULL
        CONSTRAINT chk_califhosp_puntaje CHECK (puntaje BETWEEN 1 AND 5), -- valida el rango de puntaje de calificacion
    fecha            DATE NOT NULL,
    id_paciente      INTEGER
        CONSTRAINT fk_califhosp_paciente REFERENCES paciente(id_paciente)
        ON DELETE SET NULL ON UPDATE CASCADE,
    comentario       TEXT
);
COMMENT ON TABLE calificacion_hospital IS 'Calificacion de calidad registrada para un hospital';

CREATE TABLE calificacion_medico (
    id_calificacion  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_medico        INTEGER NOT NULL
        CONSTRAINT fk_califmed_medico REFERENCES medico(id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    puntaje          SMALLINT NOT NULL
        CONSTRAINT chk_califmed_puntaje CHECK (puntaje BETWEEN 1 AND 5), -- valida el rango de puntaje de calificacion
    fecha            DATE NOT NULL,
    id_paciente      INTEGER
        CONSTRAINT fk_califmed_paciente REFERENCES paciente(id_paciente)
        ON DELETE SET NULL ON UPDATE CASCADE,
    comentario       TEXT
);
COMMENT ON TABLE calificacion_medico IS 'Calificacion de calidad registrada para un medico';

CREATE TABLE calificacion_enfermero (
    id_calificacion  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_enfermero     INTEGER NOT NULL
        CONSTRAINT fk_califenf_enfermero REFERENCES enfermero(id_enfermero)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    puntaje          SMALLINT NOT NULL
        CONSTRAINT chk_califenf_puntaje CHECK (puntaje BETWEEN 1 AND 5), -- valida el rango de puntaje de calificacion
    fecha            DATE NOT NULL,
    id_paciente      INTEGER
        CONSTRAINT fk_califenf_paciente REFERENCES paciente(id_paciente)
        ON DELETE SET NULL ON UPDATE CASCADE,
    comentario       TEXT
);
COMMENT ON TABLE calificacion_enfermero IS 'Calificacion de calidad registrada para un enfermero';

CREATE TABLE calificacion_personal_encargado (
    id_calificacion  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_encargado     INTEGER NOT NULL
        CONSTRAINT fk_califenc_encargado REFERENCES personal_encargado(id_encargado)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    puntaje          SMALLINT NOT NULL
        CONSTRAINT chk_califenc_puntaje CHECK (puntaje BETWEEN 1 AND 5), -- valida el rango de puntaje de calificacion
    fecha            DATE NOT NULL,
    id_paciente      INTEGER
        CONSTRAINT fk_califenc_paciente REFERENCES paciente(id_paciente)
        ON DELETE SET NULL ON UPDATE CASCADE,
    comentario       TEXT
);
COMMENT ON TABLE calificacion_personal_encargado IS 'Calificacion de calidad registrada para el personal administrativo/encargado del hospital';
